/*
 Navicat Premium Data Transfer

 Source Server         : mysql
 Source Server Type    : MySQL
 Source Server Version : 100424
 Source Host           : localhost:3306
 Source Schema         : tradebox

 Target Server Type    : MySQL
 Target Server Version : 100424
 File Encoding         : 65001

 Date: 25/08/2022 08:59:58
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for language
-- ----------------------------
DROP TABLE IF EXISTS `language`;
CREATE TABLE `language`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `phrase` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `english` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `french` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1001 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of language
-- ----------------------------
INSERT INTO `language` VALUES (1, 'creator_wallet', 'Creator Wallet Address', 'Creator Wallet Address fr');
INSERT INTO `language` VALUES (2, 'contact_address', 'Contract Address', 'Contract Address fr');
INSERT INTO `language` VALUES (3, 'email', 'Email', 'E-mail');
INSERT INTO `language` VALUES (4, 'password', 'Password', 'Mot De Passe');
INSERT INTO `language` VALUES (5, 'login', 'Login', 'S\'identifier');
INSERT INTO `language` VALUES (6, 'incorrect_email_password', 'Incorrect Email/Password!', 'Mot de passe ou email incorrect');
INSERT INTO `language` VALUES (7, 'user_role', 'User Role', 'RÃ´le Utilisateur');
INSERT INTO `language` VALUES (8, 'please_login', 'Please Login', 'Veuillez Vous Connecter');
INSERT INTO `language` VALUES (9, 'setting', 'Setting', 'Réglage');
INSERT INTO `language` VALUES (10, 'profile', 'Profile', 'Profil');
INSERT INTO `language` VALUES (11, 'logout', 'Log Out', 'DÃ©connexion');
INSERT INTO `language` VALUES (12, 'please_try_again', 'Please Try Again', 'Essayez encore !');
INSERT INTO `language` VALUES (13, 'admin', 'Admin', 'Admin');
INSERT INTO `language` VALUES (14, 'dashboard', 'Dashboard', 'Tableau de Bord');
INSERT INTO `language` VALUES (15, 'language_setting', 'Language Setting', 'Reglage Langue');
INSERT INTO `language` VALUES (16, 'status', 'Status', 'Status');
INSERT INTO `language` VALUES (17, 'active', 'Active', 'Actif');
INSERT INTO `language` VALUES (18, 'inactive', 'Inactive', 'Inactif');
INSERT INTO `language` VALUES (19, 'cancel', 'Cancel', 'Cancel');
INSERT INTO `language` VALUES (20, 'save', 'Save', 'Sauver');
INSERT INTO `language` VALUES (21, 'serial', 'Serial', 'En Série');
INSERT INTO `language` VALUES (22, 'action', 'Action', 'Action');
INSERT INTO `language` VALUES (23, 'edit', 'Edit ', 'Editer');
INSERT INTO `language` VALUES (24, 'delete', 'Delete', 'Effacer');
INSERT INTO `language` VALUES (25, 'save_successfully', 'Save Successfully!', 'Sauvegarde reussi');
INSERT INTO `language` VALUES (26, 'update_successfully', 'Updated Successfully', 'Mise Ã  jour reussi');
INSERT INTO `language` VALUES (27, 'delete_successfully', 'Delete Successfully', 'Supprimer Avec Succès');
INSERT INTO `language` VALUES (28, 'are_you_sure', 'Are You Sure', 'êtes-vous Sûr');
INSERT INTO `language` VALUES (29, 'ip_address', 'IP Address', 'Adresse IP');
INSERT INTO `language` VALUES (30, 'application_title', 'Application title', 'Titre appli');
INSERT INTO `language` VALUES (31, 'favicon', 'Favicon', 'favicon');
INSERT INTO `language` VALUES (32, 'logo', 'Logo', 'Logo');
INSERT INTO `language` VALUES (33, 'footer_text', 'Footer text', 'Footer text');
INSERT INTO `language` VALUES (34, 'language', 'Language', 'Langue');
INSERT INTO `language` VALUES (35, 'website_title', 'Website Title', 'Titre site web');
INSERT INTO `language` VALUES (36, 'invalid_logo', 'Invalid Logo', 'Logo invalide');
INSERT INTO `language` VALUES (37, 'submit_successfully', 'Submit Successfully!', 'Envoi reussi');
INSERT INTO `language` VALUES (38, 'application_setting', 'Application Setting', 'Reglages appli');
INSERT INTO `language` VALUES (39, 'invalid_favicon', 'Invalid Favicon', 'Favicon Invalide');
INSERT INTO `language` VALUES (40, 'submit', 'Submit', 'Envoyez');
INSERT INTO `language` VALUES (41, 'site_align', 'Website Align', 'Alignement site');
INSERT INTO `language` VALUES (42, 'right_to_left', 'Right to Left', 'Doite vers la gauche');
INSERT INTO `language` VALUES (43, 'left_to_right', 'Left to Right', 'Gauche Vers la droite');
INSERT INTO `language` VALUES (44, 'subject', 'Subject', 'Sujet');
INSERT INTO `language` VALUES (45, 'receiver_name', 'Send To', 'Nom BÃ©nÃ©ficiaire');
INSERT INTO `language` VALUES (46, 'select_user', 'Select User', 'Selectionner Utilisateur');
INSERT INTO `language` VALUES (47, 'message_sent', 'Messages Sent', 'Message EnvoyÃ©');
INSERT INTO `language` VALUES (48, 'mail', 'Mail', 'Mail');
INSERT INTO `language` VALUES (49, 'send_mail', 'Send Mail', 'Envoyer Mail');
INSERT INTO `language` VALUES (50, 'mail_setting', 'Mail Setting', 'Reglage mail');
INSERT INTO `language` VALUES (51, 'protocol', 'Protocol', 'Protocole');
INSERT INTO `language` VALUES (52, 'mailpath', 'Mail Path', 'Repertoire Mail');
INSERT INTO `language` VALUES (53, 'mailtype', 'Mail Type', 'Type mail');
INSERT INTO `language` VALUES (54, 'validate_email', 'Validate Email Address', 'Validez votre Email');
INSERT INTO `language` VALUES (55, 'true', 'True', 'Vraie');
INSERT INTO `language` VALUES (56, 'false', 'False', 'faux');
INSERT INTO `language` VALUES (57, 'attach_file', 'Attach File', 'Joindre un document');
INSERT INTO `language` VALUES (58, 'wordwrap', 'Enable Word Wrap', 'Wordwrap');
INSERT INTO `language` VALUES (59, 'send', 'Send', 'Envoyer');
INSERT INTO `language` VALUES (60, 'app_setting', 'App Setting', 'Reglages appli');
INSERT INTO `language` VALUES (61, 'sms', 'SMS', 'SMS');
INSERT INTO `language` VALUES (62, 'gateway_setting', 'Gateway Setting', 'Reglage portail');
INSERT INTO `language` VALUES (63, 'time_zone', 'Time zone', 'Time Zone');
INSERT INTO `language` VALUES (64, 'provider', 'Provider', 'Fournisseur');
INSERT INTO `language` VALUES (65, 'sms_template', 'SMS Template', 'Template SMS');
INSERT INTO `language` VALUES (66, 'template_name', 'Template Name', 'Nom du template');
INSERT INTO `language` VALUES (67, 'sms_schedule', 'SMS Schedule', 'Emploi du temps SMS');
INSERT INTO `language` VALUES (68, 'schedule_name', 'Schedule Name', 'Nom d\'horaire');
INSERT INTO `language` VALUES (69, 'time', 'Time', 'Temps');
INSERT INTO `language` VALUES (70, 'already_exists', 'Already Exists', 'Existe dÃ©jÃ ');
INSERT INTO `language` VALUES (71, 'send_custom_sms', 'Send Custom SMS', 'Envoyer SMS personalisÃ©');
INSERT INTO `language` VALUES (72, 'sms_sent', 'SMS Sent!', 'SMS envoyÃ©');
INSERT INTO `language` VALUES (73, 'custom_sms_list', 'Custom SMS List', 'List SMS personalisÃ©');
INSERT INTO `language` VALUES (74, 'reciver', 'Reciver', 'BÃ©nÃ©ficiaire');
INSERT INTO `language` VALUES (75, 'auto_sms_report', 'Auto SMS Report', 'Rapport SMS Auto');
INSERT INTO `language` VALUES (76, 'user_sms_list', 'User SMS List', 'Liste SMS utilisateurs');
INSERT INTO `language` VALUES (77, 'send_sms', 'Send SMS', 'Envoyer SMS');
INSERT INTO `language` VALUES (78, 'new_sms', 'New SMS', 'Nouveau Message');
INSERT INTO `language` VALUES (79, 'update', 'Update', 'Mettre à Jour');
INSERT INTO `language` VALUES (80, 'reset', 'Reset', 'Réinitialiser');
INSERT INTO `language` VALUES (81, 'messages', 'Messages', 'Messages');
INSERT INTO `language` VALUES (82, 'inbox', 'Inbox', 'Boite de rÃ©ception');
INSERT INTO `language` VALUES (83, 'sent', 'Sent', 'EnvoyÃ©');
INSERT INTO `language` VALUES (84, 'captcha', 'Captcha', 'Captcha');
INSERT INTO `language` VALUES (85, 'welcome_back', 'Welcome back ', 'Bienvenue Ã  nouveau !');
INSERT INTO `language` VALUES (86, 'inbox_message', 'Inbox Message', 'SMS Boite de rÃ©ception');
INSERT INTO `language` VALUES (87, 'image_upload_successfully', 'Image Upload Successfully.', 'Upload d\'image reussi');
INSERT INTO `language` VALUES (88, 'users', 'Users', 'Utilisateurs');
INSERT INTO `language` VALUES (89, 'add_user', 'Add User', 'Ajouter utilisateur');
INSERT INTO `language` VALUES (90, 'user_list', 'User List', 'Liste Utilisateurs');
INSERT INTO `language` VALUES (91, 'firstname', 'First Name', 'Nom');
INSERT INTO `language` VALUES (92, 'lastname', 'Last Name', 'PrÃ©noms');
INSERT INTO `language` VALUES (93, 'about', 'About', 'A propos de nous');
INSERT INTO `language` VALUES (94, 'preview', 'Preview', 'Visualliser');
INSERT INTO `language` VALUES (95, 'last_login', 'Last Login', 'Dernière Connexion');
INSERT INTO `language` VALUES (96, 'last_logout', 'Last Logout', 'Dernière Déconnexion');
INSERT INTO `language` VALUES (97, 'image', 'Image', 'Image');
INSERT INTO `language` VALUES (98, 'fullname', 'Full Name', 'Nom Complet');
INSERT INTO `language` VALUES (99, 'new_message', 'New Message', 'Nouveau Message');
INSERT INTO `language` VALUES (100, 'message', 'Message', 'Un Message');
INSERT INTO `language` VALUES (101, 'sender_name', 'Sender Name', 'Nom de l\'expÃ©diteur');
INSERT INTO `language` VALUES (102, 'sl_no', 'SL No.', 'NumÃ©ro SL');
INSERT INTO `language` VALUES (103, 'message_details', 'Message Details', 'DÃ©tails message');
INSERT INTO `language` VALUES (104, 'date', 'Date', 'Date');
INSERT INTO `language` VALUES (105, 'select_option', 'Select Option', 'f');
INSERT INTO `language` VALUES (106, 'edit_profile', 'Edit Profile', 'Editer Profile');
INSERT INTO `language` VALUES (107, 'edit_user', 'Edit User', 'Editer utilisateur');
INSERT INTO `language` VALUES (108, 'sent_message', 'Sent Message', 'Message EnvoyÃ©');
INSERT INTO `language` VALUES (109, 'sub_admin', 'Sub Admin', 'Sub Administrateur');
INSERT INTO `language` VALUES (110, 'admin_list', 'Admin List', 'List Administrateurs');
INSERT INTO `language` VALUES (111, 'add_admin', 'Add Admin', 'Ajouter Administrateur');
INSERT INTO `language` VALUES (112, 'edit_admin', 'Edit Admin', 'Modifier L\'administrateur');
INSERT INTO `language` VALUES (113, 'username', 'Username', 'Nom utilisateur');
INSERT INTO `language` VALUES (114, 'sponsor_id', 'Sponsor ID', 'ID sponsor');
INSERT INTO `language` VALUES (115, 'mobile', 'Mobile', 'Mobile');
INSERT INTO `language` VALUES (116, 'register', 'Register', 'Enregistrer');
INSERT INTO `language` VALUES (117, 'conf_password', 'Confirm Password', 'Reglage mot de passe');
INSERT INTO `language` VALUES (118, 'user_id', 'User ID', 'ID utilisateur');
INSERT INTO `language` VALUES (119, 'package', 'Package', 'Pack');
INSERT INTO `language` VALUES (120, 'create', 'Create', 'CrÃ©er');
INSERT INTO `language` VALUES (121, 'package_name', 'Package Name', 'Nom du pack');
INSERT INTO `language` VALUES (122, 'package_deatils', 'Package Deatils', 'Detail pack');
INSERT INTO `language` VALUES (123, 'package_amount', 'Package Amount', 'Montant pack');
INSERT INTO `language` VALUES (124, 'daily_roi', 'Daily ROI', 'ROI journalier');
INSERT INTO `language` VALUES (125, 'weekly_roi', 'Weekly ROI', 'ROI Hebdomadaire');
INSERT INTO `language` VALUES (126, 'monthly_roi', 'Monthly ROI', 'ROI Mensuel');
INSERT INTO `language` VALUES (127, 'yearly_roi', 'Yearly ROI', 'ROI annuel');
INSERT INTO `language` VALUES (128, 'total_percent', 'Total Percent', 'Poucentage Total');
INSERT INTO `language` VALUES (129, 'add_package', 'Add Package', 'Ajouter un Pack');
INSERT INTO `language` VALUES (130, 'transfer_add_msg', 'Transfer Successfully', 'Ajouter SMS transfert');
INSERT INTO `language` VALUES (131, 'transfer', 'Transfer', 'Transfert');
INSERT INTO `language` VALUES (132, 'deposit', 'Deposit', 'Dépôt');
INSERT INTO `language` VALUES (133, 'edit_package', 'Edit Package', 'Editer Pack');
INSERT INTO `language` VALUES (134, 'package_list', 'Package List', 'Liste Packs');
INSERT INTO `language` VALUES (135, 'withdraw', 'Withdraw', 'Se Désister');
INSERT INTO `language` VALUES (136, 'request', 'Request', 'RequÃªte');
INSERT INTO `language` VALUES (137, 'success', 'Success', 'SuccÃ¨s ! ');
INSERT INTO `language` VALUES (138, 'request_date', 'Request Date', 'Date RequÃªte');
INSERT INTO `language` VALUES (139, 'payment_method', 'Payment Method', 'Methode de paiement');
INSERT INTO `language` VALUES (140, 'amount', 'Amount', 'f');
INSERT INTO `language` VALUES (141, 'charge', 'Charge', 'Frais');
INSERT INTO `language` VALUES (142, 'total', 'Total', 'Total');
INSERT INTO `language` VALUES (143, 'comments', 'Comments', 'Commentaires');
INSERT INTO `language` VALUES (144, 'pending', 'Pending', 'En cours');
INSERT INTO `language` VALUES (145, 'cancel_date', 'Cancel Date', 'Annuler date');
INSERT INTO `language` VALUES (146, 'block_list', 'Block List', 'Liste Noire');
INSERT INTO `language` VALUES (147, 'commission', 'Commission', 'Commission');
INSERT INTO `language` VALUES (148, 'setup', 'Setup', 'Regler');
INSERT INTO `language` VALUES (149, 'setup_list', 'Setup List', 'Liste de reglage');
INSERT INTO `language` VALUES (150, 'commission_list', 'Commission List', 'Liste Commission');
INSERT INTO `language` VALUES (151, 'level_name', 'Level Name', 'Nom du stage');
INSERT INTO `language` VALUES (152, 'personal_invest', 'Personal Invest', 'Mon investissement');
INSERT INTO `language` VALUES (153, 'total_invest', 'Total Invest', 'Total Investissement');
INSERT INTO `language` VALUES (154, 'team_bonous', 'Team Bonous', 'Bonus d\'Equipe');
INSERT INTO `language` VALUES (155, 'referral_bonous', 'Referral Bonous', 'Bonus parrainage');
INSERT INTO `language` VALUES (156, 'form_submit_msg', 'Insert Successfully', 'Envoyer formulaire');
INSERT INTO `language` VALUES (157, 'transection_category', 'Transaction Category', 'CatÃ©gorie Transaction');
INSERT INTO `language` VALUES (158, 'add_deposit', 'Add Deposit', 'Effectuer un Depot');
INSERT INTO `language` VALUES (159, 'deposit_list', 'Deposit List', 'Liste depot');
INSERT INTO `language` VALUES (160, 'team', 'Team', 'Equipe');
INSERT INTO `language` VALUES (161, 'investment', 'Investment', 'Investissement personnel');
INSERT INTO `language` VALUES (162, 'notification', 'Notification', 'Notification');
INSERT INTO `language` VALUES (163, 'receiver_id', 'Receiver Id', 'ID BÃ©nÃ©ficiaire');
INSERT INTO `language` VALUES (164, 'comment', 'Comments', 'Commentaire');
INSERT INTO `language` VALUES (165, 'otp_send_to', 'OTP Send To', 'OTP envoyer Ã ');
INSERT INTO `language` VALUES (166, 'transection', 'Transaction', 'Transactions');
INSERT INTO `language` VALUES (167, 'buy', 'Buy', 'Acheter');
INSERT INTO `language` VALUES (168, 'deposit_amount', 'Deposit Amount', 'Montant Depot');
INSERT INTO `language` VALUES (169, 'deposit_method', 'Deposit Method', 'Methode depot');
INSERT INTO `language` VALUES (170, 'deposit_wallet_id', 'Deposit Wallet Id', 'Wallet ID');
INSERT INTO `language` VALUES (171, 'confirm_transfer', 'Confirm Transfer', 'Confirmer transfert');
INSERT INTO `language` VALUES (172, 'transfer_amount', 'Transfer Amount', 'Montant Transfert');
INSERT INTO `language` VALUES (173, 'enter_verify_code', 'Enter Verify Code', 'Entrer code de vÃ©rification');
INSERT INTO `language` VALUES (174, 'confirm', 'Confirm', 'Confirmer');
INSERT INTO `language` VALUES (175, 'deopsit_add_msg', 'Deposit Add Successfully.', 'Depot effectuÃ© avec succÃ¨s');
INSERT INTO `language` VALUES (176, 'transfar_recite', 'Transfer Recite', 'ReÃ§u de transfert');
INSERT INTO `language` VALUES (177, 'earn', 'Earn', 'Gagner');
INSERT INTO `language` VALUES (178, 'balance_is_unavailable', 'Balance Unavailable', 'Solde insuffisant');
INSERT INTO `language` VALUES (179, 'package_buy_successfully', 'Package Buy Successfully!', 'Achat du package reussi ! ');
INSERT INTO `language` VALUES (180, 'withdraw_recite', 'Withdraw Recite', 'ReÃ§u de retrait');
INSERT INTO `language` VALUES (181, 'withdraw_confirm', 'withdraw Confirm', 'Confirmation Retrait');
INSERT INTO `language` VALUES (182, 'change_verify', 'Confirm Verify', 'Changer Verification');
INSERT INTO `language` VALUES (183, 'change_password', 'Password Change', 'Changer mot de passe');
INSERT INTO `language` VALUES (184, 'enter_confirm_password', 'Enter Confirm Password', 'Confirmer mot de passe');
INSERT INTO `language` VALUES (185, 'enter_new_password', 'Enter New Password', 'Entrer nouveau mot de passe');
INSERT INTO `language` VALUES (186, 'enter_old_password', 'Enter Old Password', 'Entrer ancien mot de passe');
INSERT INTO `language` VALUES (187, 'change', 'Change', 'Changement');
INSERT INTO `language` VALUES (188, 'password_change_successfull', 'Password Change Successfully', 'Mot de passe changÃ© avec succÃ¨s');
INSERT INTO `language` VALUES (189, 'old_password_is_wrong', 'Old Password Is Wrong', 'Entrer ancien mot de passe incorrect');
INSERT INTO `language` VALUES (190, 'fees_setting', 'Fees Setting', 'Reglages frais');
INSERT INTO `language` VALUES (191, 'level', 'Level', 'Stage');
INSERT INTO `language` VALUES (192, 'select_level', 'Select Level', 'Selectionner stage');
INSERT INTO `language` VALUES (193, 'fees_setting_successfully', 'Fees Setting Successfully', 'Reglages Frais reussi');
INSERT INTO `language` VALUES (194, 'bitcoin', 'Bitcoin', 'Bitcoin');
INSERT INTO `language` VALUES (195, 'payeer', 'Payeer', 'Payeer');
INSERT INTO `language` VALUES (196, 'name', 'Name', 'Nom');
INSERT INTO `language` VALUES (197, 'order_id', 'Order Id', 'ID de commande');
INSERT INTO `language` VALUES (198, 'fees', 'Fees', 'Frais');
INSERT INTO `language` VALUES (199, 'period', 'Period', 'PÃ©riode');
INSERT INTO `language` VALUES (200, 'commission_ret', 'Commission Ret', 'Commission ret');
INSERT INTO `language` VALUES (201, 'title', 'Title', 'Titre');
INSERT INTO `language` VALUES (202, 'details', 'Details', 'Details');
INSERT INTO `language` VALUES (203, 'personal_info', 'Personal Information', 'Informations personnels');
INSERT INTO `language` VALUES (204, 'sponsor_info', 'Sponsor Information', 'Info Sponsor');
INSERT INTO `language` VALUES (205, 'affiliate_url', 'Affiliat Url', 'Lien parrainage');
INSERT INTO `language` VALUES (206, 'copy', 'Copy', 'Copier');
INSERT INTO `language` VALUES (207, 'my_payout', 'My Payout', 'Mes Paiements');
INSERT INTO `language` VALUES (208, 'personal_sales', 'Personal Sales', 'Ventes Personnelles');
INSERT INTO `language` VALUES (209, 'bank_details', 'Bank Details', 'Details de banque');
INSERT INTO `language` VALUES (210, 'beneficiary_name', 'Beneficiary Name', 'Nom Beneficiaire');
INSERT INTO `language` VALUES (211, 'bank_name', 'Bank Name', 'Nom de banque');
INSERT INTO `language` VALUES (212, 'branch', 'Branch', 'Branche');
INSERT INTO `language` VALUES (213, 'account_number', 'Account Number', 'NumÃ©ro de compte');
INSERT INTO `language` VALUES (214, 'ifsc_code', 'IFC Code', 'Code IFSC');
INSERT INTO `language` VALUES (215, 'account', 'Account', 'Compte');
INSERT INTO `language` VALUES (216, 'my_commission', 'My Commission', 'Mes commissions');
INSERT INTO `language` VALUES (217, 'finance', 'Finance', 'La Finance');
INSERT INTO `language` VALUES (218, 'exchange', 'Exchange', 'Echange');
INSERT INTO `language` VALUES (219, 'bitcoin_setting', 'Bitcoin Setting', 'Reglages bitcoin');
INSERT INTO `language` VALUES (220, 'payeer_setting', 'Payeer Setting', 'Reglages Payeer');
INSERT INTO `language` VALUES (221, 'bank_information', 'Bank Information', 'Infos de banque');
INSERT INTO `language` VALUES (222, 'bitcoin_wallet_id', 'Bitcoin Wallet ID', 'Wallet Bitcoin');
INSERT INTO `language` VALUES (223, 'payment_method_setting', 'Payment Method Setting', 'Reglage methode de paiement');
INSERT INTO `language` VALUES (224, 'payeer_wallet_id', 'Payeer Wallet Id', 'ID Payeer');
INSERT INTO `language` VALUES (225, 'my_package', 'My Package', 'Mes packs');
INSERT INTO `language` VALUES (226, 'my_team', 'My Team', 'Mon Equipe');
INSERT INTO `language` VALUES (227, 'receipt', 'Receipt', 'RÃ©Ã§u');
INSERT INTO `language` VALUES (228, 'withdraw_successfull', 'Withdraw Successfully', 'Retrait reussi !');
INSERT INTO `language` VALUES (229, 'team_bonus', 'Team Bonus', 'Bonus d\'Equipe');
INSERT INTO `language` VALUES (230, 'withdraw_list', 'Withdraw List', 'Liste retraits');
INSERT INTO `language` VALUES (231, 'pending_withdraw', 'Pending Withdraw', NULL);
INSERT INTO `language` VALUES (232, 'reciver_account', 'Receiver Account', 'Compte BÃ©nÃ©ficiaire');
INSERT INTO `language` VALUES (233, 'french', 'French', 'FranÃ§ais');
INSERT INTO `language` VALUES (234, 'commission_setup', 'Commission Setup', 'Reglage commission');
INSERT INTO `language` VALUES (235, 'personal_investment', 'Personal Investment', 'Investissement personnel');
INSERT INTO `language` VALUES (236, 'total_investment', 'Total investment', 'Total Investissement');
INSERT INTO `language` VALUES (237, 'transfer_list', 'Transfer List', 'Liste transfert');
INSERT INTO `language` VALUES (238, 'form_to', 'From To', '');
INSERT INTO `language` VALUES (239, 'receive', 'Receive', '');
INSERT INTO `language` VALUES (240, 'wallet_id', 'Wallet Id', 'ID Wallet');
INSERT INTO `language` VALUES (241, 'withdraw_details', 'Withdraw Details', 'Details retraits');
INSERT INTO `language` VALUES (242, 'generation_one', 'Generation One', 'GÃ©nÃ©ration 1');
INSERT INTO `language` VALUES (243, 'generation_two', 'Generation Two', 'GÃ©nÃ©ration 2');
INSERT INTO `language` VALUES (244, 'generation_three', 'Generation Three', 'GÃ©nÃ©ration 3');
INSERT INTO `language` VALUES (245, 'generation_four', 'Generation Four', 'GÃ©nÃ©ration 4');
INSERT INTO `language` VALUES (246, 'generation_five', 'Generation Five', 'GÃ©nÃ©ration 5');
INSERT INTO `language` VALUES (247, 'generation_empty_message', 'You Have No Generation', '');
INSERT INTO `language` VALUES (248, 'view', 'View', 'AperÃ§u');
INSERT INTO `language` VALUES (249, 'cancle', 'Cancel', 'Annuler');
INSERT INTO `language` VALUES (250, 'type', 'Type', 'Taper');
INSERT INTO `language` VALUES (251, 'your_total_balance_is', 'Your Total Balance Is', 'Votre montant total est de');
INSERT INTO `language` VALUES (252, 'bonus', 'Bonus', 'Bonus');
INSERT INTO `language` VALUES (253, 'personal_turnover', 'Sponser Turnover', 'Mon Chiffre d\'affaire perso');
INSERT INTO `language` VALUES (254, 'team_turnover', 'Team Turnover', 'Chiffre d\'affaire Equipe');
INSERT INTO `language` VALUES (255, 'post_article', 'Post Article', '');
INSERT INTO `language` VALUES (256, 'article_list', 'Article List', 'LIste article');
INSERT INTO `language` VALUES (257, 'add_article', 'Add Article', 'Ajouter article');
INSERT INTO `language` VALUES (258, 'headline_en', 'Headline English', 'Titre EN');
INSERT INTO `language` VALUES (259, 'headline_fr', 'Headline French', 'Titre  FR');
INSERT INTO `language` VALUES (260, 'article_en', 'Article EN', 'Article EN');
INSERT INTO `language` VALUES (261, 'article_fr', 'Article FR', 'Article FR');
INSERT INTO `language` VALUES (262, 'edit_article', 'Edit Article', 'Editer article');
INSERT INTO `language` VALUES (263, 'cat_list', 'Category List', 'Liste panier');
INSERT INTO `language` VALUES (264, 'add_cat', 'Add Category', 'Ajouter au panier');
INSERT INTO `language` VALUES (265, 'parent_cat', 'Parent Category', '');
INSERT INTO `language` VALUES (266, 'cat_name_en', 'Category Name English', 'Nom panier EN');
INSERT INTO `language` VALUES (267, 'cat_name_fr', 'Category Name French', 'Nom panier FR');
INSERT INTO `language` VALUES (268, 'cat_title_en', 'Category Title English', 'Titre Panier EN');
INSERT INTO `language` VALUES (269, 'cat_title_fr', 'Category Title French', 'Titre panier FR');
INSERT INTO `language` VALUES (270, 'select_cat', 'Select Category', 'Selectionner Cat');
INSERT INTO `language` VALUES (271, 'edit_cat', 'Edit Category', 'Editer Panier');
INSERT INTO `language` VALUES (272, 'position_serial', 'Position Serial', '');
INSERT INTO `language` VALUES (273, 'currency_list', 'Currency List', 'Liste de devise');
INSERT INTO `language` VALUES (274, 'currency', 'Currency', 'Devise');
INSERT INTO `language` VALUES (275, 'cryptocurrency_name', 'CryptoCurrency  Name', 'Nom Crypto monnaie');
INSERT INTO `language` VALUES (276, 'select_cryptocurrency', 'Select Cryptocurrency', 'Selectionner Crypto');
INSERT INTO `language` VALUES (277, 'edit_currency', 'Edit Currency', 'Editer Devise');
INSERT INTO `language` VALUES (278, 'exchange_list', 'Exchange List', 'Liste Ã©changes');
INSERT INTO `language` VALUES (279, 'add_exchange', 'Add Exchange', 'Ajouter Echange');
INSERT INTO `language` VALUES (280, 'edit_exchange', 'Edit Exchange', 'Editer Echange');
INSERT INTO `language` VALUES (281, 'wallet_data', 'Wallet ID', 'DonnÃ©es Wallet');
INSERT INTO `language` VALUES (282, 'sell_adjustment', 'Sell Adjustment', 'Ajustement Vente');
INSERT INTO `language` VALUES (283, 'buy_adjustment', 'Buy Adjustment', '');
INSERT INTO `language` VALUES (284, 'exchange_wallet', 'Exchange Wallet', 'Wallet Echange');
INSERT INTO `language` VALUES (285, 'exchange_wallet_list', 'Exchange Wallet List', 'Liste Wallet echange');
INSERT INTO `language` VALUES (286, 'add_exchange_wallet', 'Add Exchange Wallet', 'Ajouter Wallet');
INSERT INTO `language` VALUES (287, 'edit_exchange_wallet', 'Edit Exchange Wallet', 'Modifier Wallet echange');
INSERT INTO `language` VALUES (288, 'local_currency_list', 'Local Currency List', 'LIste  Monnaies locales');
INSERT INTO `language` VALUES (289, 'local_currency', 'Local Currency', 'Devise Locale');
INSERT INTO `language` VALUES (290, 'add_local_currency', 'Add Local Currency', 'Ajouter Monnaie');
INSERT INTO `language` VALUES (291, 'edit_local_currency', 'Edit Local Currency', 'Editer Devise locale');
INSERT INTO `language` VALUES (292, 'currency_name', 'Currency Name', 'Nom devise');
INSERT INTO `language` VALUES (293, 'currency_iso_code', 'Currency ISO Code', 'Code ISO devise ');
INSERT INTO `language` VALUES (294, 'usd_exchange_rate', 'USD Exchange Rate', 'Taux d\'echange USD');
INSERT INTO `language` VALUES (295, 'currency_symbol', 'Currency Symbol', 'Symboles Devise');
INSERT INTO `language` VALUES (296, 'symbol_position', 'Symbol Position', 'Position symbole');
INSERT INTO `language` VALUES (297, 'currency_position', 'Currency Position', 'Position devise');
INSERT INTO `language` VALUES (298, 'payment_gateway', 'Payment Gateway', 'Portail de paiement');
INSERT INTO `language` VALUES (299, 'gateway_name', 'Gateway Name', 'Nom passerelle');
INSERT INTO `language` VALUES (300, 'gateway_setting', 'Gateway Setting', 'Reglage portail');
INSERT INTO `language` VALUES (301, 'add_payment_gateway', 'Add Payment Gateway', 'Ajouter Methode paiment');
INSERT INTO `language` VALUES (302, 'public_key', 'Public Key', 'ClÃ© publique');
INSERT INTO `language` VALUES (303, 'private_key', 'Private Key', '');
INSERT INTO `language` VALUES (304, 'shop_id', 'Shop ID', 'ID shop');
INSERT INTO `language` VALUES (305, 'secret_key', 'Secret Key', 'ClÃ© secrete');
INSERT INTO `language` VALUES (306, 'edit_payment_gateway', 'Edit Payment Gateway', 'Editer Methode de paiement');
INSERT INTO `language` VALUES (307, 'slider_list', 'Slider List', '');
INSERT INTO `language` VALUES (308, 'add_slider', 'Add Slider', 'Ajouter Slider');
INSERT INTO `language` VALUES (309, 'headline', 'Headline', 'Titre');
INSERT INTO `language` VALUES (310, 'edit_slider', 'Edit Slider', '');
INSERT INTO `language` VALUES (311, 'social_app', 'Social App', '');
INSERT INTO `language` VALUES (312, 'edit_social_app', 'Edit Social App', 'Editer RS appli');
INSERT INTO `language` VALUES (313, 'social_link', 'Social Link', '');
INSERT INTO `language` VALUES (314, 'add_link', 'Add Link', 'Ajouter Lien');
INSERT INTO `language` VALUES (315, 'link', 'Link', 'Lien');
INSERT INTO `language` VALUES (316, 'icon', 'Icon', 'IcÃ´ne');
INSERT INTO `language` VALUES (317, 'edit_social_link', 'Edit Social Link', 'Edit les liens RS');
INSERT INTO `language` VALUES (318, 'transection_info', 'Transection Info', 'Info transaction');
INSERT INTO `language` VALUES (319, 'sell', 'Sell', 'Vendre');
INSERT INTO `language` VALUES (320, 'article', 'Article', 'Article');
INSERT INTO `language` VALUES (321, 'coin_amount', 'Coin Amount', 'Montat Crypto');
INSERT INTO `language` VALUES (322, 'coin_name', 'Coin Name', NULL);
INSERT INTO `language` VALUES (323, 'buy_amount', 'Buy Amount', 'Montant achat');
INSERT INTO `language` VALUES (324, 'sell_amount', 'Sell Amount', 'Montant Ã  vendre');
INSERT INTO `language` VALUES (325, 'wallet_data', 'Wallet ID', 'DonnÃ©es Wallet');
INSERT INTO `language` VALUES (326, 'usd_amount', 'USD Amount', 'Montant USD');
INSERT INTO `language` VALUES (327, 'rate_coin', 'Coin Rate', 'Taux coin');
INSERT INTO `language` VALUES (328, 'local_amount', 'Local Amount', 'Montant Local');
INSERT INTO `language` VALUES (329, 'om_name', 'OM Name', 'Nom OM');
INSERT INTO `language` VALUES (330, 'om_mobile_no', 'OM Phone No', 'NÂ° OM');
INSERT INTO `language` VALUES (331, 'transaction_no', 'Transaction No', 'NÂ° de transaction');
INSERT INTO `language` VALUES (332, 'idcard_no', 'ID Card No', 'NÂ° CNI');
INSERT INTO `language` VALUES (333, 'buy_list', 'Buy List', 'Buy list');
INSERT INTO `language` VALUES (334, 'add_buy', 'Add Buy', 'Ajouter Achat');
INSERT INTO `language` VALUES (335, 'transection_type', 'Transection Type', 'Type de transaction');
INSERT INTO `language` VALUES (336, 'payment_successfully', 'Payment Successfully', 'Paiement effectuÃ©');
INSERT INTO `language` VALUES (337, 'payment_cancel', 'Payment Cancel', 'Paiement annulÃ©');
INSERT INTO `language` VALUES (338, 'payment_successfully', 'Payment Successfully', 'Paiement effectuÃ©');
INSERT INTO `language` VALUES (339, 'sell_list', 'Sell List', 'LIste de vente ');
INSERT INTO `language` VALUES (340, 'add_sell', 'Add Sell', 'Ajouter Vente');
INSERT INTO `language` VALUES (341, 'edit_sell', 'Edit Sell', '');
INSERT INTO `language` VALUES (342, 'account_active_mail', 'Please check Email to activate your account', 'Activer votre mail');
INSERT INTO `language` VALUES (343, 'accept_terms_privacy', 'Crypto Privacy policy and Terms of Use', 'Accepter conditions et termes');
INSERT INTO `language` VALUES (344, 'username_used', 'Username Already Used', 'Nom d\'utilisateur dÃ©jÃ  utilisÃ©');
INSERT INTO `language` VALUES (345, 'account_create_success_social', 'Account Created Successfully and Your Account activated', 'Compte crÃ©e avec succÃ¨s');
INSERT INTO `language` VALUES (346, 'email_used', 'Email Already Used', 'Adresse mail dÃ©jÃ  utilisÃ©');
INSERT INTO `language` VALUES (347, 'account_create_active_link', 'Account Created Successfully. Activation link send your Email address', 'Lien d\'activation');
INSERT INTO `language` VALUES (348, 'active_account', 'Active Account', 'Compte actif');
INSERT INTO `language` VALUES (349, 'wrong_try_activation', 'Wrong Try', 'Mauvaise activation');
INSERT INTO `language` VALUES (350, 'pay_now', 'Pay Now', 'Payer maintenant');
INSERT INTO `language` VALUES (351, 'payment_successfully', 'Payment Successfully', 'Paiement effectuÃ©');
INSERT INTO `language` VALUES (352, 'sell_successfully', 'Sell Successfully', 'Vente effectuÃ©e avec succÃ¨s');
INSERT INTO `language` VALUES (353, 'already_clicked', 'Already Clicked There', 'DÃ©ja ValidÃ©');
INSERT INTO `language` VALUES (354, 'user_info', 'User Info', 'info utilisateur');
INSERT INTO `language` VALUES (355, 'user_id', 'User ID', 'ID utilisateur');
INSERT INTO `language` VALUES (356, 'registered_ip', 'Registered IP', '');
INSERT INTO `language` VALUES (357, 'requested_ip', 'Requested IP', '');
INSERT INTO `language` VALUES (358, 'transaction_status', 'Transaction Status', 'Status de la transaction');
INSERT INTO `language` VALUES (359, 'receive_status', 'receive_status', '');
INSERT INTO `language` VALUES (360, 'receive_complete', 'Receive Complete', '');
INSERT INTO `language` VALUES (361, 'payment_status', 'Payment Status', 'Status de paiement');
INSERT INTO `language` VALUES (362, 'payment_complete', 'Payment Complete', NULL);
INSERT INTO `language` VALUES (363, 'url', 'Url', 'URL');
INSERT INTO `language` VALUES (364, 'app_id', 'App Id', 'ID appli');
INSERT INTO `language` VALUES (365, 'app_secret', 'App Secret', 'Secret Appli');
INSERT INTO `language` VALUES (366, 'api_key', 'API Key', 'Clé API');
INSERT INTO `language` VALUES (367, 'app_name', 'App Name', 'Nom Appli');
INSERT INTO `language` VALUES (368, 'social_list', 'Social List', '');
INSERT INTO `language` VALUES (369, 'select_payment_method', 'Select Payment Method', 'Selectionner mode de paiement');
INSERT INTO `language` VALUES (370, 'payable', 'Payable', '');
INSERT INTO `language` VALUES (371, 'rate', 'Rate', NULL);
INSERT INTO `language` VALUES (372, 'how_do_you_receive_money', 'How do you receive money', 'Comment ReÃ§evoir votre argent');
INSERT INTO `language` VALUES (373, 'withdraw_method', 'Withdraw Method', 'Methode de retrait');
INSERT INTO `language` VALUES (374, 'select_withdraw_method', 'Select Withdraw Method', 'Selectionner mÃ©thode de retrait');
INSERT INTO `language` VALUES (375, 'account_info', 'Account Info', 'Info compte');
INSERT INTO `language` VALUES (376, 'upload_docunemts', 'Upload Docunemts', 'Ajouter fichier');
INSERT INTO `language` VALUES (377, 'my_generation', 'My Generation', 'Mon Equipe');
INSERT INTO `language` VALUES (378, 'category', 'Category', 'CatÃ©gorie');
INSERT INTO `language` VALUES (379, 'slider_h1_en', 'Slider H1 English', '');
INSERT INTO `language` VALUES (380, 'slider_h1_fr', 'Slider H1 French', '');
INSERT INTO `language` VALUES (381, 'slider_h2_en', 'Slider H2 English', '');
INSERT INTO `language` VALUES (382, 'slider_h2_fr', 'Slider H2 French', '');
INSERT INTO `language` VALUES (383, 'slider_h3_en', 'Slider H3 English', '');
INSERT INTO `language` VALUES (384, 'slider_h3_fr', 'Slider H3 French', '');
INSERT INTO `language` VALUES (385, 'complete', 'Complete', NULL);
INSERT INTO `language` VALUES (386, 'refresh_currency', 'Refresh Currency', '');
INSERT INTO `language` VALUES (387, 'cryptocurrency', 'Crypto Currency', 'Crypto Monnaie');
INSERT INTO `language` VALUES (388, 'symbol', 'Symbol', NULL);
INSERT INTO `language` VALUES (389, 'please_select_cryptocurrency_first', 'Please Select CryptoCurrency First', 'Veuillez choisir une crypto monnaie');
INSERT INTO `language` VALUES (390, 'please_select_diffrent_payment_method', 'Please select Diffrent Payment Method', 'Selectionner une autre mÃ©thode de paiement');
INSERT INTO `language` VALUES (391, 'add_credit', 'Add Credit', 'Crediter Compte');
INSERT INTO `language` VALUES (392, 'credit', 'Credit', 'CrÃ©dit');
INSERT INTO `language` VALUES (393, 'credit_list', 'Credit List', 'Liste De Crédit');
INSERT INTO `language` VALUES (394, 'notes', 'Note', 'Notes');
INSERT INTO `language` VALUES (395, 'my_level_info', 'My Level Info', 'Info Niveau');
INSERT INTO `language` VALUES (396, 'slider', 'Slider', 'Slider');
INSERT INTO `language` VALUES (397, 'exchange_setting', 'Exchange Setting', 'Reglage Echange');
INSERT INTO `language` VALUES (398, 'exchange_all_request', 'Exchange all Request', 'Toutes requÃªtes echanges');
INSERT INTO `language` VALUES (399, 'total_user', 'Total User', 'Nombre d\'utilisateurs');
INSERT INTO `language` VALUES (400, 'total_roi', 'Total ROI', 'Total ROI');
INSERT INTO `language` VALUES (401, 'total_commission', 'Total Commission', 'Total commission');
INSERT INTO `language` VALUES (402, 'download_pdf', 'Download PDF', 'TÃ©lÃ©charger ');
INSERT INTO `language` VALUES (403, 'view_all_news', 'View all news', 'AperÃ§u News');
INSERT INTO `language` VALUES (404, 'download_company_brochure', 'Download Company Brochure', 'TÃ©lÃ©chargez notre brochure');
INSERT INTO `language` VALUES (405, 'get_in_touch', 'Get in touch', 'Contactez-nous');
INSERT INTO `language` VALUES (406, 'read_more', 'Read More', 'Lire plus');
INSERT INTO `language` VALUES (407, 'know_more', 'Know more', 'Savoir plus');
INSERT INTO `language` VALUES (408, 'choose_plan', 'Choose plan', 'acheter');
INSERT INTO `language` VALUES (409, 'latest_jobs', 'Latest Jobs', 'Latest Jobs');
INSERT INTO `language` VALUES (410, 'website', 'Website', 'website');
INSERT INTO `language` VALUES (411, 'chose_one_of_the_following_methods', 'Chose One of the Following Methods.', 'chose_one_of_the_following_methods.');
INSERT INTO `language` VALUES (412, 'sign_in_using_your_email_address', 'Sign in Using Your Email Address', 'Connectez-vous avec votre username ou email');
INSERT INTO `language` VALUES (413, 'forgot_password', 'Forgot Password', 'Mot De Passe Oublié');
INSERT INTO `language` VALUES (414, 'remember_me', 'Remember Me', 'Souviens-toi De Moi');
INSERT INTO `language` VALUES (415, 'username_or_email', 'Username or email', 'Username or email');
INSERT INTO `language` VALUES (416, 'dont_have_an_account', 'Don\'t have an account', 'Don\'t have an account');
INSERT INTO `language` VALUES (417, 'sign_up_now', 'Sign up Now', 'CrÃ©er un compte maintenant');
INSERT INTO `language` VALUES (418, 'send_code', 'Send Code', 'Send Code');
INSERT INTO `language` VALUES (419, 'sign_up', 'Sign Up', 'S\'inscrire');
INSERT INTO `language` VALUES (420, 'already_user', 'Already User', 'Already User');
INSERT INTO `language` VALUES (421, 'sign_in_now', 'Sign In Now', 'Connectez-vous maintenant');
INSERT INTO `language` VALUES (422, 'sign_up_for_free', 'Sign Up For Free', 'CrÃ©er un compte gratuitement');
INSERT INTO `language` VALUES (423, 'join_thousands_of_companies_that_Use_globalcrypt_every_day', 'Join Thousands of Companies that Use Global Crypto Every Day', 'Join Thousands of Companies that Use Global Crypto Every Day');
INSERT INTO `language` VALUES (424, 'your_password_at_global_crypto_are_encrypted_and_secured', 'Your Password At Global Crypto Are Encrypted And Secured', 'Votre Mot De Passe Chez Global Crypto Est Crypté Et Sécurisé');
INSERT INTO `language` VALUES (425, 'email_username_used', 'Email/Username Already Used', 'Email/Username Already Used');
INSERT INTO `language` VALUES (426, 'address', 'Address', 'Adresse');
INSERT INTO `language` VALUES (427, 'phone', 'Phone', 'Phone');
INSERT INTO `language` VALUES (428, 'admin_align', 'Admin alignment', 'Admin alignment');
INSERT INTO `language` VALUES (429, 'office_time', 'Office time', 'Office time');
INSERT INTO `language` VALUES (430, 'logo_web', 'Website logo', 'Website logo');
INSERT INTO `language` VALUES (431, 'dashboard_logo', 'Dashboard logo', 'Dashboard logo');
INSERT INTO `language` VALUES (432, 'advertisement', 'Advertisement', 'Advertisement');
INSERT INTO `language` VALUES (433, 'script', 'Script', 'Script');
INSERT INTO `language` VALUES (434, 'add_advertisement', 'Add Advertisement', 'Add Advertisement');
INSERT INTO `language` VALUES (435, 'page', 'Page', NULL);
INSERT INTO `language` VALUES (436, 'embed_code', 'Embed code', 'Embed code');
INSERT INTO `language` VALUES (437, 'add_type', 'Add Type', 'Add Type');
INSERT INTO `language` VALUES (438, 'edit_advertisement', 'Edit Advertisement', 'Edit Advertisement');
INSERT INTO `language` VALUES (439, 'host', 'Host', 'Host');
INSERT INTO `language` VALUES (440, 'port', 'Port', 'Port');
INSERT INTO `language` VALUES (441, 'apikey', 'API Key', 'API Key');
INSERT INTO `language` VALUES (442, 'mail_type', 'Mail Type', 'Mail Type');
INSERT INTO `language` VALUES (443, 'charset', 'Charset', 'Charset');
INSERT INTO `language` VALUES (444, 'news', 'News', 'Nouvelles');
INSERT INTO `language` VALUES (445, 'news_list', 'News List', 'News List');
INSERT INTO `language` VALUES (446, 'edit_news', 'Edit News', 'Edit News');
INSERT INTO `language` VALUES (447, 'post_news', 'Post News', 'Post News');
INSERT INTO `language` VALUES (448, 'close', 'Close', 'Close');
INSERT INTO `language` VALUES (449, 'contact_us', 'Contact Us', 'Contact Us');
INSERT INTO `language` VALUES (450, 'watch_video', 'WATCH VIDEO', 'WATCH VIDEO');
INSERT INTO `language` VALUES (451, 'about_bitcoin', 'About Bitcoin', 'About Bitcoin');
INSERT INTO `language` VALUES (452, 'get_start', 'Get Start', 'Get Start');
INSERT INTO `language` VALUES (453, 'cryptocoins', 'Crypto Coins', 'Crypto Coins');
INSERT INTO `language` VALUES (454, 'subscribe_to_our_newsletter', 'Subscribe to our newsletter!', 'Subscribe to our newsletter!');
INSERT INTO `language` VALUES (455, 'email_newslatter', 'Email Newsletter', 'Email Newsletter');
INSERT INTO `language` VALUES (456, 'services', 'Services', 'Services');
INSERT INTO `language` VALUES (457, 'our_company', 'Our Company', 'Our Company');
INSERT INTO `language` VALUES (458, 'sign_in', 'Sign In', 'Connectez-vous');
INSERT INTO `language` VALUES (459, 'join_the_new_yera_of_cryptocurrency_exchange', 'Join the new Yera of cryptocurrency exchange', 'Join the new Yera of cryptocurrency exchange');
INSERT INTO `language` VALUES (460, 'access_the_cryptocurrency_experience_you_deserve', 'Access the cryptocurrency experience you deserve', 'Access the cryptocurrency experience you deserve');
INSERT INTO `language` VALUES (461, 'home', 'Home', 'Accueil');
INSERT INTO `language` VALUES (462, 'scroll_to_top', 'Scroll to Top', 'Scroll to Top');
INSERT INTO `language` VALUES (463, 'ticker', 'Ticker', 'Ticker');
INSERT INTO `language` VALUES (464, 'price', 'Price', 'Prix');
INSERT INTO `language` VALUES (465, 'capitalization', 'Capitalization', 'Capitalization');
INSERT INTO `language` VALUES (466, '1d_change', '1D change', '1D change');
INSERT INTO `language` VALUES (467, 'graph_24h', 'Graph 24H', 'Graph 24H');
INSERT INTO `language` VALUES (468, 'recent_post', 'Recent Post', 'Recent Post');
INSERT INTO `language` VALUES (469, 'my_social_link', 'My Social link', 'My Social link');
INSERT INTO `language` VALUES (470, 'tell_us_about_your_project', 'Tell Us About Your Project', 'Tell Us About Your Project');
INSERT INTO `language` VALUES (471, 'company', 'Company', 'Company');
INSERT INTO `language` VALUES (472, 'reset_your_password', 'Reset Your Password', 'Réinitialisez Votre Mot De Passe');
INSERT INTO `language` VALUES (473, '24h_change', '24H change', '24H change');
INSERT INTO `language` VALUES (474, '24h_volume', '24H Volume', '24H Volume');
INSERT INTO `language` VALUES (475, 'latitudelongitude', 'Latitude, Longitude', 'Latitude, Longitude');
INSERT INTO `language` VALUES (476, 'send_money', 'Send Money', 'Send Money');
INSERT INTO `language` VALUES (477, 'article', 'Article', 'article');
INSERT INTO `language` VALUES (478, 'contact', 'Contact', 'Contact');
INSERT INTO `language` VALUES (479, 'team', 'Team', 'team');
INSERT INTO `language` VALUES (480, 'client', 'Client', 'client');
INSERT INTO `language` VALUES (481, 'service', 'Service', 'service');
INSERT INTO `language` VALUES (482, 'testimonial', 'Testimonial', 'testimonial');
INSERT INTO `language` VALUES (483, 'faq', 'F.A.Q', 'faq');
INSERT INTO `language` VALUES (484, 'short_description_en', 'Short description english', 'Short Description');
INSERT INTO `language` VALUES (485, 'long_description_en', 'Long description English', 'Long Description');
INSERT INTO `language` VALUES (486, 'short_description_fr', 'Short description english', 'Short Description');
INSERT INTO `language` VALUES (487, 'long_description_fr', 'Long description English', 'Long Description');
INSERT INTO `language` VALUES (488, 'info', 'Information', 'Information');
INSERT INTO `language` VALUES (489, 'quote', 'Quote', 'Quote');
INSERT INTO `language` VALUES (490, 'question_fr', 'Question French', 'Question French');
INSERT INTO `language` VALUES (491, 'question_en', 'Question English', 'Question English');
INSERT INTO `language` VALUES (492, 'answer_en', 'Answer English', 'Answer English');
INSERT INTO `language` VALUES (493, 'answer_fr', 'Answer French', 'Answer French');
INSERT INTO `language` VALUES (494, 'content', 'Page Content', 'Page Content');
INSERT INTO `language` VALUES (495, 'add_content', 'Add Content', 'Add Content');
INSERT INTO `language` VALUES (496, 'edit_content', 'Edit Content', 'Edit Content');
INSERT INTO `language` VALUES (497, 'video', 'video (If Youtube Link)', 'video');
INSERT INTO `language` VALUES (498, 'add_faq', 'Add F.A.Q', 'Add faq');
INSERT INTO `language` VALUES (499, 'add_testimonial', 'Add Testimonial', 'Add testimonial');
INSERT INTO `language` VALUES (500, 'add_service', 'Add Service', 'Add service');
INSERT INTO `language` VALUES (501, 'add_client', 'Add Client', 'Add client');
INSERT INTO `language` VALUES (502, 'add_team', 'Add Team', 'Add team');
INSERT INTO `language` VALUES (503, 'add_contact', 'Add Contact', 'Add contact');
INSERT INTO `language` VALUES (504, 'add_article', 'Add Article', 'Add article');
INSERT INTO `language` VALUES (505, 'edit_article', 'edit Article', 'edit article');
INSERT INTO `language` VALUES (506, 'edit_contact', 'edit Contact', 'edit contact');
INSERT INTO `language` VALUES (507, 'edit_team', 'edit Team', 'edit team');
INSERT INTO `language` VALUES (508, 'edit_client', 'edit Client', 'edit client');
INSERT INTO `language` VALUES (509, 'edit_service', 'edit Service', 'edit service');
INSERT INTO `language` VALUES (510, 'edit_testimonial', 'edit Testimonial', 'edit testimonial');
INSERT INTO `language` VALUES (511, 'edit_faq', 'edit F.A.Q', 'edit faq');
INSERT INTO `language` VALUES (512, 'article_list', 'Article List', 'article');
INSERT INTO `language` VALUES (513, 'contact_list', 'Contact List', 'contact');
INSERT INTO `language` VALUES (514, 'team_list', 'Team List', 'team');
INSERT INTO `language` VALUES (515, 'client_list', 'Client List', 'client');
INSERT INTO `language` VALUES (516, 'service_list', 'Service List', 'service');
INSERT INTO `language` VALUES (517, 'testimonial_list', 'Testimonial List', 'testimonial');
INSERT INTO `language` VALUES (518, 'faq_list', 'F.A.Q List', 'faq');
INSERT INTO `language` VALUES (519, 'content_list', 'Page Content', 'Page Content');
INSERT INTO `language` VALUES (520, 'add_teammember', 'Add Teammember', 'Add Teammember');
INSERT INTO `language` VALUES (521, 'tooltip_package_name', 'Example: Silver Package', 'Example: Silver Package');
INSERT INTO `language` VALUES (522, 'tooltip_package_details', 'This is for Package Short Details', 'This is for Package Short Details.');
INSERT INTO `language` VALUES (523, 'tooltip_package_amount', 'Package Amount in Dollar. Example: 200', 'Package Amount in Dollar. Example: 200');
INSERT INTO `language` VALUES (524, 'tooltip_package_daily_roi', 'Please Set this field with Zero. Example: 0', 'Please Set this field with Zero. Example: 0');
INSERT INTO `language` VALUES (525, 'tooltip_package_weekly_roi', 'Who buy this package they will get weekly ROI in Dollar. Example: 5. They will get every week 5 till them package period', 'Who buy this package they will get weekly ROI in Dollar. Example: 5. They will get every week 5 till them package period');
INSERT INTO `language` VALUES (526, 'tooltip_package_monthly_roi', 'Sum of weekly ROI in a month', 'Sum of weekly ROI in a month');
INSERT INTO `language` VALUES (527, 'tooltip_package_yearly_roi', 'Sum of weekly ROI in a Year', 'Sum of weekly ROI in a Year');
INSERT INTO `language` VALUES (528, 'tooltip_package_total_percent_roi', 'Total Persent Of ROI', 'Total Persent Of ROI');
INSERT INTO `language` VALUES (529, 'tooltip_package_period', 'Package Period', 'Package Period');
INSERT INTO `language` VALUES (530, 'trading', 'Trading', 'Trade');
INSERT INTO `language` VALUES (531, 'trade_history', 'Trade History', 'Histoire Du Commerce');
INSERT INTO `language` VALUES (532, 'market', 'Market', 'Marché');
INSERT INTO `language` VALUES (533, 'coin_pair', 'Coin Pair', 'Coin Pair');
INSERT INTO `language` VALUES (534, 'pending_deposit', 'Pending Deposit', 'Demande de retrat en cours');
INSERT INTO `language` VALUES (535, 'email_and_sms_setting', 'Email And SMS Setting', 'Paramètres D\'e-mail Et De SMS');
INSERT INTO `language` VALUES (536, 'email_and_sms_gateway', 'Email And Sms Gateway', 'Email And Sms Gateway');
INSERT INTO `language` VALUES (537, 'trade', 'Trade', 'Commerce');
INSERT INTO `language` VALUES (538, 'referral_id', 'Referral ID', '');
INSERT INTO `language` VALUES (539, 'please_enter_valid_email', 'Please Enter Valid Email !!!', 'Please Enter Valid Email !!!');
INSERT INTO `language` VALUES (540, 'already_subscribe', 'This Email Address already subscribed', 'This Email Address already subscribed');
INSERT INTO `language` VALUES (541, 'message_send_successfuly', 'TMessage send successfuly', 'Message send successfuly');
INSERT INTO `language` VALUES (542, 'message_send_fail', 'Message send Fail', 'Message send Fail');
INSERT INTO `language` VALUES (543, 'setup_payment_gateway', 'setup payment gateway', 'setup payment gateway');
INSERT INTO `language` VALUES (544, 'user_profile', 'User Profile', 'User Profile');
INSERT INTO `language` VALUES (545, 'client_id', 'Client Id', 'Client Id');
INSERT INTO `language` VALUES (546, 'client_secret', 'Client Secret', 'Client Secret');
INSERT INTO `language` VALUES (547, 'notice', 'Notice', 'Remarquer');
INSERT INTO `language` VALUES (548, 'edit_notice', 'Edit Notice', 'Edit Notice');
INSERT INTO `language` VALUES (549, 'language_list', 'Language List', 'Language List');
INSERT INTO `language` VALUES (550, 'phrase_list', 'Phrase List', 'Phrase List');
INSERT INTO `language` VALUES (551, 'edit_phrase', 'Edit Phrase', 'Edit Phrase');
INSERT INTO `language` VALUES (552, 'label_added_successfully', 'Label added successfully!', 'Label added successfully!');
INSERT INTO `language` VALUES (553, 'this_level_already_exist', 'This Level Already Exist!', 'This Level Already Exist!');
INSERT INTO `language` VALUES (554, 'you_successfully_deposit_the_amount', 'You successfully deposit the amount', 'You successfully deposit the amount');
INSERT INTO `language` VALUES (555, 'your_new_balance_is', 'Your new balance is', 'Your new balance is');
INSERT INTO `language` VALUES (556, 'account_name', 'Account Name', 'Account Name');
INSERT INTO `language` VALUES (557, 'account_no', 'Account No', 'Account No');
INSERT INTO `language` VALUES (558, 'branch_name', 'Branch Name', 'Branch Name');
INSERT INTO `language` VALUES (559, 'swift_code', 'SWIFT Code', 'SWIFT Code');
INSERT INTO `language` VALUES (560, 'abn_no', 'ABN No', 'ABN No');
INSERT INTO `language` VALUES (561, 'country', 'Country', 'Country');
INSERT INTO `language` VALUES (562, 'bank_name', 'Bank Name', 'Bank Name');
INSERT INTO `language` VALUES (563, 'there_is_no_phone_number', 'There is no Phone number!!!', 'There is no Phone number!!!');
INSERT INTO `language` VALUES (564, 'coinpair', 'Coinpair', 'Coinpair');
INSERT INTO `language` VALUES (565, 'edit_coinpair', 'Edit Coinpair', 'Edit Coinpair');
INSERT INTO `language` VALUES (566, 'edit_coin', 'Edit coin', 'Edit coin');
INSERT INTO `language` VALUES (567, 'coin_market', 'Coin Market', 'Marché Aux Pièces');
INSERT INTO `language` VALUES (568, 'edit_market', 'Edit Market', 'Modifier Le Marché');
INSERT INTO `language` VALUES (569, 'leave_us_a_message', 'Leave us a message', 'Leave us a message');
INSERT INTO `language` VALUES (570, 'verify_type', 'verify type', 'verify type');
INSERT INTO `language` VALUES (571, 'gender', 'Gender', 'Gender');
INSERT INTO `language` VALUES (572, 'id_number', 'Id  Number', 'Id Number');
INSERT INTO `language` VALUES (573, 'verification_is_being_processed', 'Verification Is being Processed', 'Verification Is being Processed');
INSERT INTO `language` VALUES (574, 'cryptocoin', 'Cryptocoin', 'Cryptocoin french');
INSERT INTO `language` VALUES (575, 'please_setup_your_bank_account', 'Please setup bank account', 'Please setup bank account');
INSERT INTO `language` VALUES (576, 'this_gateway_deactivated', 'This Gateway Deactivated', 'This Gateway Deactivated');
INSERT INTO `language` VALUES (577, 'otp_send_to', 'OTP Send To', 'OTP Send To');
INSERT INTO `language` VALUES (578, 'your_weekly_limit_exceeded', 'Your weekly Limit exceeded', 'Your weekly exceeded ');
INSERT INTO `language` VALUES (579, 'there_is_no_order_for_cancel', 'There is no order for cancel', 'There is no order for cancel');
INSERT INTO `language` VALUES (580, 'request_canceled', 'Request Canceled', 'Demande Annulée');
INSERT INTO `language` VALUES (581, 'referral_id_is_invalid', 'Referral ID is invalid', 'Referral ID is invalid');
INSERT INTO `language` VALUES (582, 'invalid_ip_address', 'Invalid IP address', 'Invalid IP address');
INSERT INTO `language` VALUES (583, 'please_activate_your_account', 'Please activate your account', 'Please activate your account');
INSERT INTO `language` VALUES (584, 'already_regsister', 'Already regsister!!!', 'Already regsister!!!');
INSERT INTO `language` VALUES (585, 'this_account_is_now_pending', 'This account is now pending', 'This account is now pending');
INSERT INTO `language` VALUES (586, 'this_account_is_suspend', 'This account is suspend', 'This account is suspend');
INSERT INTO `language` VALUES (587, 'something_wrong', 'Something wrong !!!', 'Something wrong !!!');
INSERT INTO `language` VALUES (588, 'password_missmatch', 'Password Missmatch', 'password missmatch');
INSERT INTO `language` VALUES (589, 'invalid_authentication_code', 'Invalid Authentication Code', 'Invalid Authentication Code');
INSERT INTO `language` VALUES (590, 'password_reset_code_send_check_your_email', 'Password reset code send.Check your email.', 'Password reset code send.Check your email.');
INSERT INTO `language` VALUES (591, 'email_required', 'email required', 'email required');
INSERT INTO `language` VALUES (592, 'password_changed', 'Password has been changed', 'Password has been changed');
INSERT INTO `language` VALUES (593, 'google_authenticator_disabled', 'Google Authenticator Disabled', 'Google Authenticator Disabled');
INSERT INTO `language` VALUES (594, 'google_authenticator_enabled', 'Google Authenticator Enabled', 'Google Authenticator Enabled');
INSERT INTO `language` VALUES (595, 'this_account_already_activated', 'This account already activated', 'This account already activated');
INSERT INTO `language` VALUES (596, 'total_balance', 'Total Balance', 'Total Balance');
INSERT INTO `language` VALUES (597, 'available_balance', 'Available Balance', 'Available balance');
INSERT INTO `language` VALUES (598, 'open', 'Open', NULL);
INSERT INTO `language` VALUES (599, 'qty', 'QTY', 'QTY');
INSERT INTO `language` VALUES (600, 'finished_trade', 'Finished Trade', 'Finished Trade');
INSERT INTO `language` VALUES (601, 'deposit_crypto_dollar', 'Deposit(Crypto/Dollar)', 'Deposit(Crypto/Dollar)');
INSERT INTO `language` VALUES (602, 'us_dollar', 'US Dollar', 'US Dollar');
INSERT INTO `language` VALUES (603, 'available', 'Available', 'Disponible');
INSERT INTO `language` VALUES (604, 'buy_orders', 'Buy Orders', 'Buy Orders');
INSERT INTO `language` VALUES (605, 'last_price', 'Last price', 'last price');
INSERT INTO `language` VALUES (606, 'sell_orders', 'Sell Orders', 'Sell Orders');
INSERT INTO `language` VALUES (607, '1hr_change', '1hr Change', '1hr Change');
INSERT INTO `language` VALUES (608, '1hr_high', '1hr High', '1hr High');
INSERT INTO `language` VALUES (609, '1hr_low', '1hr Low', '1hr Low');
INSERT INTO `language` VALUES (610, '1hr_volume', '1hr Volume', '1hr Volume');
INSERT INTO `language` VALUES (611, 'estimated_open_price', 'Estimated open price', 'Estimated open price');
INSERT INTO `language` VALUES (612, 'open_fees', 'Open fees', 'Open fees');
INSERT INTO `language` VALUES (613, 'market_depth', 'Market Depth', 'Market Depth');
INSERT INTO `language` VALUES (614, 'coin', 'Coin', 'Pièce De Monnaie');
INSERT INTO `language` VALUES (615, 'market_price', 'Market Price', 'Market Price');
INSERT INTO `language` VALUES (616, 'volume', 'volume', 'volume');
INSERT INTO `language` VALUES (617, 'live_chat', 'Live Chat', 'Live Chat');
INSERT INTO `language` VALUES (618, 'market_trade_history', 'Market Trade History', 'Market Trade History');
INSERT INTO `language` VALUES (619, 'Notices', 'notices', 'notices');
INSERT INTO `language` VALUES (620, 'posted_by', 'Posted by', 'Posted by');
INSERT INTO `language` VALUES (621, 'latest_form_our_blog', 'Latest form our blog', 'Latest form our blog');
INSERT INTO `language` VALUES (622, 'auth_code', 'Auth Code', 'AuthCode');
INSERT INTO `language` VALUES (623, 'scan_this_barcode_using', 'Scan this BarCode using', 'Scan this BarCode using');
INSERT INTO `language` VALUES (624, 'google_authentication', 'Google Authentication', 'Google Authentication');
INSERT INTO `language` VALUES (625, 'install_google_authentication', 'Install Google Authentication', 'Install Google Authentication');
INSERT INTO `language` VALUES (626, 'if_you_are_unable_to_scan_the_qr_code_please_enter_this_code_manually_into_the_app.', 'If you are unable to scan the QR code, please enter this code manually into the app.', 'If you are unable to scan the QR code, please enter this code manually into the app.');
INSERT INTO `language` VALUES (627, 'open_order', 'Open Order', 'Open Order');
INSERT INTO `language` VALUES (628, 'complete_order', 'Complete Order', 'Complete Order');
INSERT INTO `language` VALUES (629, 'bank_setting', 'Bank Setup', 'Bank Setup');
INSERT INTO `language` VALUES (630, 'payout_setup', 'Payout Setup', 'Payout Setup');
INSERT INTO `language` VALUES (631, 'account_login', 'Account Login', 'Account Login');
INSERT INTO `language` VALUES (632, 'we_never_share_your_email_with_anyone_else', 'We\'ll never share your email with anyone else', 'We\'ll never share your email with anyone else');
INSERT INTO `language` VALUES (633, 'news_details', 'News Details', 'News Details');
INSERT INTO `language` VALUES (634, 'open_order_history', 'Open Order History', 'Open Order History');
INSERT INTO `language` VALUES (635, 'required_qty', 'Required QTY', '');
INSERT INTO `language` VALUES (636, 'available_qty', 'Available Quantity ', '');
INSERT INTO `language` VALUES (637, 'required_amount', 'Required Amount', '');
INSERT INTO `language` VALUES (638, 'available_amount', 'Available Amount', '');
INSERT INTO `language` VALUES (639, 'complete_qty', 'Complete QTY', '');
INSERT INTO `language` VALUES (640, 'complete_amount', 'Complete amount', '');
INSERT INTO `language` VALUES (641, 'trade_time', 'Trade Time', 'Trade Time');
INSERT INTO `language` VALUES (642, 'running', 'Running', NULL);
INSERT INTO `language` VALUES (643, '24hr_change', '24hr Change', '24hr Change');
INSERT INTO `language` VALUES (644, '24hr_high', '24hr High', '24hr High');
INSERT INTO `language` VALUES (645, '24hr_low', '24hr Low', '1hr Low');
INSERT INTO `language` VALUES (646, '24hr_volume', '24hr Volume', '24hr Volume');
INSERT INTO `language` VALUES (647, 'post_comment', 'Post Comment', 'Post Comment');
INSERT INTO `language` VALUES (648, 'account_created', 'Account Created', 'Account Created');
INSERT INTO `language` VALUES (649, 'access_time', 'Access Time', 'Access Time');
INSERT INTO `language` VALUES (650, 'user_agent', 'User Agent', 'User Agent');
INSERT INTO `language` VALUES (651, 'passport', 'Passport', 'Passport');
INSERT INTO `language` VALUES (652, 'drivers_license', 'Driver license', 'Driver license');
INSERT INTO `language` VALUES (653, 'government_issued_id_card', 'Government-issued ID Card', 'Government-issued ID Card');
INSERT INTO `language` VALUES (654, 'given_name', 'Given Name', 'Given Name');
INSERT INTO `language` VALUES (655, 'surname', 'Surname', 'Surname');
INSERT INTO `language` VALUES (656, 'passport_nid_license_number', 'Passport/NID/License Number', 'Passport/NID/License Number');
INSERT INTO `language` VALUES (657, 'account_register', 'Account Register', 'Account Register');
INSERT INTO `language` VALUES (658, 'confirm_password', 'Confirm Password', 'Confirm Password');
INSERT INTO `language` VALUES (659, 'canceled', 'Canceled', NULL);
INSERT INTO `language` VALUES (660, 'completed', 'Completed', NULL);
INSERT INTO `language` VALUES (661, 'crypto_dollar_currency', 'Crypto/Dollar Currency', 'Crypto/Dollar Currency');
INSERT INTO `language` VALUES (662, 'withdraw_no', 'Withdraw No', 'Withdraw No');
INSERT INTO `language` VALUES (663, 'male', 'Male', 'Male');
INSERT INTO `language` VALUES (664, 'female', 'Female', 'Female');
INSERT INTO `language` VALUES (665, 'verify', 'Verify', 'Verify');
INSERT INTO `language` VALUES (666, 'server_problem', 'Server Problem', 'Server Problem');
INSERT INTO `language` VALUES (667, 'verified', 'Verified', 'Vérifié');
INSERT INTO `language` VALUES (668, 'footer_menu1', 'Footer menu 1', 'Footer menu 1');
INSERT INTO `language` VALUES (669, 'footer_menu2', 'Footer menu 2', 'Footer menu 2');
INSERT INTO `language` VALUES (670, 'footer_menu3', 'Social Service', 'Social Service');
INSERT INTO `language` VALUES (671, 'terms_of_use', 'Terms Of Use', 'Terms Of Use');
INSERT INTO `language` VALUES (672, 'receiver_not_valid', 'Receiver not valid!!!', 'Receiver not valid!!!');
INSERT INTO `language` VALUES (673, 'first_name_required', 'Please enter your name!', 'Please enter your name!');
INSERT INTO `language` VALUES (674, 'a_lowercase_letter', 'Please Enter a Lowercase letter !', 'Please enter a loswercase letter!');
INSERT INTO `language` VALUES (675, 'password_required', 'Please enter your password!', 'Please enter yYour password!');
INSERT INTO `language` VALUES (676, 'a_capital_uppercase_letter', 'Please Enter a Uppercase letter ! ', 'Please enter a upercase letter!');
INSERT INTO `language` VALUES (677, 'a_number', 'Please Enter a Number!', 'Please enter a number!');
INSERT INTO `language` VALUES (678, 'a_special', 'Please Enter a Special Character !', 'Please enter a  special character!');
INSERT INTO `language` VALUES (679, 'please_enter_at_least_8_characters_input', 'Please enter at least eight characters!', 'Please enter at least eight characters!');
INSERT INTO `language` VALUES (680, 'confirm_password_must_be_filled_out', 'Please enter Confirm password!', 'Please enter Confirm password!');
INSERT INTO `language` VALUES (681, 'must_confirm_privacy_policy_and_terms_and_conditions', 'Must confirm privacy policy and terms and conditions', 'Must confirm privacy policy and terms and conditions');
INSERT INTO `language` VALUES (682, 'phone_required', 'Enter your phone number!', 'Enter your phone number!');
INSERT INTO `language` VALUES (683, 'email_required', 'Enter your email address!', 'Enter your email address!');
INSERT INTO `language` VALUES (684, 'comments_required', 'Enter your comments!', 'Enter your comments!');
INSERT INTO `language` VALUES (685, 'first_name', 'Please enter your first name!', 'Please enter your first name!');
INSERT INTO `language` VALUES (686, 'c', NULL, NULL);
INSERT INTO `language` VALUES (687, 'f_name', 'First Name', 'First Name');
INSERT INTO `language` VALUES (688, 'l_name', 'Last Name', 'Last Name');
INSERT INTO `language` VALUES (689, 'coin_full_name', 'Coin Full Name', 'Nom complet de la piÃ¨ce');
INSERT INTO `language` VALUES (690, 'coin_id', 'Coin Id', 'ID de piÃ¨ce');
INSERT INTO `language` VALUES (691, 'rank', 'Rank', NULL);
INSERT INTO `language` VALUES (692, 'show_home', 'Show Home', 'Afficher la maison');
INSERT INTO `language` VALUES (693, 'yes', 'Yes', 'Oui');
INSERT INTO `language` VALUES (694, 'no', 'No', 'Non');
INSERT INTO `language` VALUES (695, 'coin_image/icon/logo', 'Coin Image/Icon/Logo', 'Image de piÃ¨ce / icÃ´ne / logo');
INSERT INTO `language` VALUES (696, 'coin_icon', 'Coin Icon', 'IcÃ´ne de piÃ¨ce de monnaie');
INSERT INTO `language` VALUES (697, 'full_name', 'Full Name', 'Nom complet');
INSERT INTO `language` VALUES (698, 'home_page/serial', 'Home Page/Serial', 'Page d\'accueil / SÃ©rie');
INSERT INTO `language` VALUES (699, 'email_notification_settings', 'Email Notification Settings', 'Paramètres De Notification Par E-mail');
INSERT INTO `language` VALUES (700, 'payout', 'Payout', NULL);
INSERT INTO `language` VALUES (701, 'commissin', 'Commissin', 'Commission');
INSERT INTO `language` VALUES (702, 'team_bonnus', 'Team Bonnus', NULL);
INSERT INTO `language` VALUES (703, 'sms_sending', 'SMS Sending', 'Envoi De SMS');
INSERT INTO `language` VALUES (704, 'exchange_market', 'Exchange Market', 'Marché Des Changes');
INSERT INTO `language` VALUES (705, 'total_trade', 'Total Trade', 'Commerce Total');
INSERT INTO `language` VALUES (706, 'total_crypto_fees', 'Total Crypto Fees', 'Total Des Frais De Crypto');
INSERT INTO `language` VALUES (707, 'total_usd_fees', 'Total USD Fees', 'Frais Totaux En USD');
INSERT INTO `language` VALUES (708, 'referral_bonus_usd', 'Referral Bonus USD', 'Bonus De Parrainage USD');
INSERT INTO `language` VALUES (709, 'market_deposit', 'Market Deposit', 'DÃ©pÃ´t de marchÃ©');
INSERT INTO `language` VALUES (710, 'fees_collect', 'Fees Collect', 'Frais collectÃ©s');
INSERT INTO `language` VALUES (711, 'quantity', 'Quantity', 'QuantitÃ©');
INSERT INTO `language` VALUES (712, 'required', 'Required', NULL);
INSERT INTO `language` VALUES (713, 'history', 'history', 'histoire');
INSERT INTO `language` VALUES (714, 'back', 'Back', 'Retour');
INSERT INTO `language` VALUES (715, 'important', 'Important', 'Important');
INSERT INTO `language` VALUES (716, 'send_only', 'Send Only', 'Envoyer seulement');
INSERT INTO `language` VALUES (717, 'deposit_address', 'deposit address', 'adresse de dÃ©pÃ´t');
INSERT INTO `language` VALUES (718, 'sending_any_other_coin_or_token_to_this_address_may_result_in_the_loss_of_your_deposit', 'Sending any other coin or token to this address may result in the loss of your deposit', 'L\'envoi de toute autre piÃ¨ce ou jeton Ã  cette adresse peut entraÃ®ner la perte de votre dÃ©pÃ´t');
INSERT INTO `language` VALUES (719, 'copy_address', 'Copy Address', 'Copier l\'adresse');
INSERT INTO `language` VALUES (720, 'payment_process', 'Payment Process', NULL);
INSERT INTO `language` VALUES (721, 'balance', 'Balance', 'Ã©quilibre');
INSERT INTO `language` VALUES (722, 'flag', 'Flag', NULL);
INSERT INTO `language` VALUES (723, 'menu_background_color', 'Menu Background Color', 'Couleur d\'arrière-plan du menu');
INSERT INTO `language` VALUES (724, 'menu_font_color', 'Menu Font Color', 'Couleur de la police du menu');
INSERT INTO `language` VALUES (725, 'footer_background_color', 'Footer Background Color', 'Couleur de fond du bas de page');
INSERT INTO `language` VALUES (726, 'footer_font_color', 'Footer Font Color', 'Couleur de la police du pied de page');
INSERT INTO `language` VALUES (727, 'button_background_color', 'Button Background Color', 'Couleur d\'arrière-plan du bouton');
INSERT INTO `language` VALUES (728, 'button_font_color', 'Button Font Color', 'Couleur de la police du bouton');
INSERT INTO `language` VALUES (729, 'theme_color', 'Theme Color', 'Couleur du thème');
INSERT INTO `language` VALUES (730, 'newsletter_background_color', 'Newsletter Background Color', 'Couleur d\'arrière-plan de la newsletter');
INSERT INTO `language` VALUES (731, 'newsletter_font_color', 'Newsletter Font Color', 'Couleur de police de la newsletter');
INSERT INTO `language` VALUES (732, 'newsletter_images', 'Newsletter Images', 'Images de la newsletter');
INSERT INTO `language` VALUES (733, 'pending-withdraw', 'Pending withdraw', 'En attente de retrait');
INSERT INTO `language` VALUES (734, 'withdraw-list', 'Withdraw List', 'Retirer la liste');
INSERT INTO `language` VALUES (735, 'pending-deposit', 'Pending Deposit', 'Dépôt en attente');
INSERT INTO `language` VALUES (736, 'deposit-list', 'Deposit List', 'Liste de dépôt');
INSERT INTO `language` VALUES (737, 'add-credit', 'Add Credit', 'Ajouter un crédit');
INSERT INTO `language` VALUES (738, 'open-order', 'Open Order', 'Commande Ouverte');
INSERT INTO `language` VALUES (739, 'trade-history', 'Trade History', 'Histoire Du Commerce');
INSERT INTO `language` VALUES (740, 'exchanger', 'Exchanger', 'Échangeur');
INSERT INTO `language` VALUES (741, 'coin-pair', 'Coin Pair', 'Paire De Pièces');
INSERT INTO `language` VALUES (742, 'user', 'User', 'Utilisateur');
INSERT INTO `language` VALUES (743, 'add-user', 'Add User', 'Ajouter un utilisateur');
INSERT INTO `language` VALUES (744, 'user-list', 'user list', 'liste d\'utilisateur');
INSERT INTO `language` VALUES (745, 'verify-user', 'Verify User', 'Vérifier L\'utilisateur');
INSERT INTO `language` VALUES (746, 'subscriber-list', 'Subscriber List', 'Liste D\'abonnés');
INSERT INTO `language` VALUES (747, 'app-setting', 'App Setting', 'Réglage De L\'application');
INSERT INTO `language` VALUES (748, 'block-list', 'Block List', 'Liste De Blocage');
INSERT INTO `language` VALUES (749, 'fees-setting', 'Fees Setting', 'établissement Des Frais');
INSERT INTO `language` VALUES (750, 'transaction-setup', 'Transaction Setup', 'Configuration De La Transaction');
INSERT INTO `language` VALUES (751, 'email-sms-gateway', 'Email Sms Gateway', 'Passerelle Sms Email');
INSERT INTO `language` VALUES (752, 'payment-gateway', 'Payment Gateway', 'Passerelle De Paiement');
INSERT INTO `language` VALUES (753, 'affiliation', 'Affiliation', 'Affiliation');
INSERT INTO `language` VALUES (754, 'external-api-list', 'External Api List', 'Liste Des API Externes');
INSERT INTO `language` VALUES (755, 'update-external-api', 'Update External Api', 'Mettre à Jour L\'API Externe');
INSERT INTO `language` VALUES (756, 'phrase', 'Phrase', 'Phrase');
INSERT INTO `language` VALUES (757, 'edit-phrase', 'Edit Phrase', 'Modifier La Phrase');
INSERT INTO `language` VALUES (758, 'update-gateway', 'Update Gateway', 'Mettre à Jour La Passerelle');
INSERT INTO `language` VALUES (759, 'edit-user', 'Edit User', 'Modifier L\'utilisateur');
INSERT INTO `language` VALUES (760, 'add-admin', 'Add Admin', 'Ajouter Un Administrateur');
INSERT INTO `language` VALUES (761, 'admin-list', 'Admin List', 'Liste D\'administrateurs');
INSERT INTO `language` VALUES (762, 'cms', 'CMS', 'CMS');
INSERT INTO `language` VALUES (763, 'themes-setting', 'Themes Setting', 'Réglage Des Thèmes');
INSERT INTO `language` VALUES (764, 'page-content-list', 'Page Content List', 'Liste De Contenu De Page');
INSERT INTO `language` VALUES (765, 'faq-list', 'Faq List', 'Liste De Faq');
INSERT INTO `language` VALUES (766, 'notice-list', 'Notice List', 'Liste D\'avis');
INSERT INTO `language` VALUES (767, 'edit-page-content', 'Edit Page Content', 'Modifier Le Contenu De La Page');
INSERT INTO `language` VALUES (768, 'edit-faq', 'Edit Faq', 'Modifier La FAQ');
INSERT INTO `language` VALUES (769, 'edit-notice', 'Edit Notice', 'Modifier L\'avis');
INSERT INTO `language` VALUES (770, 'add-page-content', 'Add Page Content', 'Ajouter Du Contenu De Page');
INSERT INTO `language` VALUES (771, 'add-faq', 'Add Faq', 'Ajouter Une FAQ');
INSERT INTO `language` VALUES (772, 'news-list', 'News List', 'Liste De Nouvelles');
INSERT INTO `language` VALUES (773, 'add-news', 'Add News', 'Ajouter Des Nouvelles');
INSERT INTO `language` VALUES (774, 'edit-news', 'Edit News', 'Modifier Les Actualités');
INSERT INTO `language` VALUES (775, 'category-list', 'Category List', 'Liste Des Catégories');
INSERT INTO `language` VALUES (776, 'add-category', 'Add Category', 'Ajouter Une Catégorie');
INSERT INTO `language` VALUES (777, 'edit-category', 'Edit Category', 'Modifier La Catégorie');
INSERT INTO `language` VALUES (778, 'slider-list', 'Slider List', 'Liste De Curseurs');
INSERT INTO `language` VALUES (779, 'add-slider', 'Add Slider', 'Ajouter Un Curseur');
INSERT INTO `language` VALUES (780, 'edit-slider', 'Edit Slider', 'Modifier Le Curseur');
INSERT INTO `language` VALUES (781, 'social-link-list', 'Social Link List', 'Liste De Liens Sociaux');
INSERT INTO `language` VALUES (782, 'edit-social-link', 'Edit Social Link', 'Modifier Le Lien Social');
INSERT INTO `language` VALUES (783, 'advertisement-list', 'Advertisement List', 'Liste De Publicités');
INSERT INTO `language` VALUES (784, 'add-advertisement', 'Add Advertisement', 'Ajouter Une Publicité');
INSERT INTO `language` VALUES (785, 'edit-advertisement', 'Edit Advertisement', 'Modifier La Publicité');
INSERT INTO `language` VALUES (786, 'web-language-list', 'Web Language List', 'Liste Des Langues Web');
INSERT INTO `language` VALUES (787, 'autoupdate', 'Autoupdate', 'Mise à Jour Automatique');
INSERT INTO `language` VALUES (788, 'latest-version', 'Latest Version', 'Dernière Version');
INSERT INTO `language` VALUES (789, 'current-version', 'Current Version', 'Version Actuelle');
INSERT INTO `language` VALUES (790, 'subscriber', 'Subscriber', 'Abonné');
INSERT INTO `language` VALUES (791, 'affiliation-setup', 'Affiliation Setup', 'Configuration De L\'affiliation');
INSERT INTO `language` VALUES (792, 'external-api', 'External API', 'API Externe');
INSERT INTO `language` VALUES (793, 'support', 'Support', 'Soutien');
INSERT INTO `language` VALUES (794, 'no-update-available', 'No Update Available', 'Pas De Mise A Jour Disponible');
INSERT INTO `language` VALUES (795, 'full-name', 'Full Name', 'Nom Complet');
INSERT INTO `language` VALUES (796, 'initial-price', 'Initial Price', 'Prix ???initial');
INSERT INTO `language` VALUES (797, 'test_bdtask', 'Bdtask Limited', NULL);
INSERT INTO `language` VALUES (798, 'email_sms_template', 'E-mail And SMS Template', 'E-mail And SMS Template');
INSERT INTO `language` VALUES (799, 'template-english', 'Template English', 'Modèle Anglais');
INSERT INTO `language` VALUES (800, 'template-french', 'Template French', 'Modèle Français');
INSERT INTO `language` VALUES (801, 'template-name', 'Template Name', 'Nom Du Modèle');
INSERT INTO `language` VALUES (802, 'template-type', 'Template Type', 'Type De Modèle');
INSERT INTO `language` VALUES (803, 'template-update', 'Template-update', 'Template-update');
INSERT INTO `language` VALUES (804, 'email-sms-template', 'Email Sms Template', 'Modèle De Courrier électronique SMS');
INSERT INTO `language` VALUES (805, 'transfer_verification', 'Transfer Verification', 'Vérification Du Transfert');
INSERT INTO `language` VALUES (806, 'transfer_success', 'Transfer Success', 'Succès Du Transfert');
INSERT INTO `language` VALUES (807, 'withdraw_verification', 'Withdraw Verification', 'Retirer La Vérification');
INSERT INTO `language` VALUES (808, 'withdraw_success', 'Withdraw Success', 'Retirer Le Succès');
INSERT INTO `language` VALUES (809, 'profile_update', 'Profile Update', 'Mise à Jour Du Profil');
INSERT INTO `language` VALUES (810, 'deposit_success', 'Deposit Success', 'Réussite Du Dépôt');
INSERT INTO `language` VALUES (811, 'registered', 'Registered', 'Inscrit');
INSERT INTO `language` VALUES (812, 'email_address', 'Email Address', 'Adresse E-mail');
INSERT INTO `language` VALUES (813, 'template_type', 'Template Type', 'Type De Modèle');
INSERT INTO `language` VALUES (814, 'subject_english', 'Subject English', 'Sujet Anglais');
INSERT INTO `language` VALUES (815, 'subject_french', 'Subject French', 'Sujet Français');
INSERT INTO `language` VALUES (816, 'purchase_key', 'Purchase Key', 'Clé D\'achat');
INSERT INTO `language` VALUES (817, 'module', 'Module', 'Module');
INSERT INTO `language` VALUES (818, 'add_module', 'Add Module', 'Ajouter Un Module');
INSERT INTO `language` VALUES (819, 'overwrite', 'Overwrite', 'écraser');
INSERT INTO `language` VALUES (820, 'theme_uploaded_successfully', 'Theme Uploaded Successfully', 'Thème Téléchargé Avec Succès');
INSERT INTO `language` VALUES (821, 'there_was_a_problem_with_the_upload', 'There Was A Problem With The Upload', 'Il Y A Eu Un Problème Avec Le Téléchargement');
INSERT INTO `language` VALUES (822, 'invalid_purchase_key', 'Invalid Purchase Key', 'Clé D\'achat Invalide');
INSERT INTO `language` VALUES (823, 'buy_now', 'Buy Now', 'Acheter Maintenant');
INSERT INTO `language` VALUES (824, 'install', 'Install', 'Installer');
INSERT INTO `language` VALUES (825, 'invalid_module', 'Invalid Module', 'Module Invalide');
INSERT INTO `language` VALUES (826, 'module_added_successfully', 'Module Added Successfully', 'Module Ajouté Avec Succès');
INSERT INTO `language` VALUES (827, 'no_tables_are_registered_in_config', 'No Tables Are Registered_in Config', 'Aucune Table N\'est Enregistrée Dans La Configuration');
INSERT INTO `language` VALUES (828, 'themes', 'Themes', 'Thèmes');
INSERT INTO `language` VALUES (829, 'module_list', 'Module List', 'Liste Des Modules');
INSERT INTO `language` VALUES (830, 'theme_active_successfully', 'Theme Active Successfully', 'Thème Actif Avec Succès');
INSERT INTO `language` VALUES (831, 'theme_name', 'Theme Name', 'Nom Du Thème');
INSERT INTO `language` VALUES (832, 'upload', 'Upload', 'Télécharger');
INSERT INTO `language` VALUES (833, 'downloaded_successfully', 'Downloaded Successfully', 'Téléchargé Avec Succès');
INSERT INTO `language` VALUES (834, 'failed_try_again', 'Failed Try Again', 'échec Réessayer');
INSERT INTO `language` VALUES (835, 'no_theme_available', 'No Theme Available', 'Aucun Thème Disponible');
INSERT INTO `language` VALUES (836, 'download', 'Download', 'Télécharger');
INSERT INTO `language` VALUES (837, 'theme_list', 'Theme List', 'Liste De Thèmes');
INSERT INTO `language` VALUES (838, 'addon', 'Addon', 'Ajouter');
INSERT INTO `language` VALUES (839, 'add_theme', 'Add Theme', 'Ajouter Un Thème');
INSERT INTO `language` VALUES (840, 'download_theme', 'Download Theme', 'Télécharger Le Thème');
INSERT INTO `language` VALUES (841, 'uninstall', 'Uninstall', 'Désinstaller');
INSERT INTO `language` VALUES (842, 'please_wait', 'Please Wait', 'S\'il Vous Plaît, Attendez');
INSERT INTO `language` VALUES (843, 'current', 'Current', 'Actuel');
INSERT INTO `language` VALUES (844, 'back_to_home', 'Back To Home', 'De Retour à La Maison');
INSERT INTO `language` VALUES (845, 'trading_history', 'Trading History', 'Historique Du Trading');
INSERT INTO `language` VALUES (846, 'latest_news', 'Latest News', 'Dernières Nouvelles');
INSERT INTO `language` VALUES (847, 'create_an_account', 'Create An Account', 'Créer Un Compte');
INSERT INTO `language` VALUES (848, 'to__trade', 'To  Trade', 'échanger');
INSERT INTO `language` VALUES (849, 'log_in', 'Log In', 'S\'identifier');
INSERT INTO `language` VALUES (850, 'white', 'WHITE', 'BLANC');
INSERT INTO `language` VALUES (851, 'dark', 'DARK', 'FONCÉ');
INSERT INTO `language` VALUES (852, 'enter_your_email_address_to_retrieve_your_password', 'Enter Your Email Address To Retrieve Your Password', 'Entrez Votre Adresse E-mail Pour Récupérer Votre Mot De Passe');
INSERT INTO `language` VALUES (853, 'retrieve_password', 'Retrieve Password', 'Récupérer Mot De Passe');
INSERT INTO `language` VALUES (854, 'not_a_member_yet', 'Not A Member Yet', 'Pas Encore Membre');
INSERT INTO `language` VALUES (855, 'total_users', 'Total Users', 'Nombre Total D\'utilisateurs');
INSERT INTO `language` VALUES (856, 'all_users', 'All Users', 'Tous Les Utilisateurs');
INSERT INTO `language` VALUES (857, 'all_markets', 'All Markets', 'Tous Les Marchés');
INSERT INTO `language` VALUES (858, 'method', 'Method', 'Méthode');
INSERT INTO `language` VALUES (859, 'slider_title_engnilsh', 'Slider Title Engnilsh', 'Titre Du Curseur Engnilsh');
INSERT INTO `language` VALUES (860, 'slider_h1', 'Slider H1', 'Curseur H1');
INSERT INTO `language` VALUES (861, 'sub_title_english', 'Sub Title English', 'Sous-titre Anglais');
INSERT INTO `language` VALUES (862, 'slider_h2', 'Slider H2', 'Curseur H2');
INSERT INTO `language` VALUES (863, 'button_text', 'Button Text', 'Texte Du Bouton');
INSERT INTO `language` VALUES (864, 'slider_h3', 'Slider H3', 'Curseur H3');
INSERT INTO `language` VALUES (865, 'code', 'Code', 'Code');
INSERT INTO `language` VALUES (866, 'language_name', 'Language Name', 'Nom De La Langue');
INSERT INTO `language` VALUES (867, 'add_coin_pair', 'Add Coin Pair', 'Ajouter Une Paire De Pièces');
INSERT INTO `language` VALUES (868, 'cryptocoin_add', 'Cryptocoin Add', 'Ajout De Crypto-monnaie');
INSERT INTO `language` VALUES (869, 'add-coin-pair', 'Add-coin-pair', 'Ajouter Une Paire De Pièces');
INSERT INTO `language` VALUES (870, 'security', 'Security', 'Sécurité');
INSERT INTO `language` VALUES (871, 'edita_dmin', 'Edita Dmin', 'Edita Dmin');
INSERT INTO `language` VALUES (872, 'edit-admin', 'Edit-admin', 'Edit-admin');
INSERT INTO `language` VALUES (873, 'article1_en', 'Article1 En', 'Article1 Fr');
INSERT INTO `language` VALUES (874, 'question_english', 'Question English', 'Question Anglais');
INSERT INTO `language` VALUES (875, 'add-notice', 'Add-notice', 'Add-notice');
INSERT INTO `language` VALUES (876, 'edit-profile', 'Edit-profile', 'Editer Le Profil');
INSERT INTO `language` VALUES (877, '_phrase_name', ' Phrase Name', 'Nom De La Phrase');
INSERT INTO `language` VALUES (878, 'cryptocoin-edit', 'Cryptocoin-edit', 'Crypto-monnaie-modifier');
INSERT INTO `language` VALUES (879, 'edit-market', 'Edit-market', 'Edit-market');
INSERT INTO `language` VALUES (880, 'edit-coin-pair', 'Edit-coin-pair', 'Modifier La Paire De Pièces');
INSERT INTO `language` VALUES (881, 'transaction_type', 'Transaction Type', 'Type De Transaction');
INSERT INTO `language` VALUES (882, 'account_type', 'Account Type', 'Type De Compte');
INSERT INTO `language` VALUES (883, 'unverified', 'Unverified', 'Non Vérifié');
INSERT INTO `language` VALUES (884, 'limit_amount', 'Limit Amount', 'Montant Limite');
INSERT INTO `language` VALUES (885, 'percent', 'Percent', 'Pour Cent');
INSERT INTO `language` VALUES (886, 'fixed', 'Fixed', 'Fixé');
INSERT INTO `language` VALUES (887, 'api_name', 'API Name', 'Nom De L\'API');
INSERT INTO `language` VALUES (888, 'merchant_id', 'Merchant Id', 'Identifiant Du Marchand');
INSERT INTO `language` VALUES (889, 'email_gateway', 'Email Gateway', 'Passerelle De Messagerie');
INSERT INTO `language` VALUES (890, 'sms_gateway', 'Sms Gateway', 'Passerelle Sms');
INSERT INTO `language` VALUES (891, 'credit-list', 'Credit-list', 'Liste De Crédit');
INSERT INTO `language` VALUES (892, 'cryptocoin-add', 'Cryptocoin-add', 'Ajout De Crypto-monnaie');
INSERT INTO `language` VALUES (893, 'see_all_users', 'See All Users', 'Voir Tous Les Utilisateurs');
INSERT INTO `language` VALUES (894, 'see_all_markets', 'See All Markets', 'Voir Tous Les Marchés');
INSERT INTO `language` VALUES (895, 'see_trade_history', 'See Trade History', 'Voir L\'historique Du Commerce');
INSERT INTO `language` VALUES (896, 'buy_&_sell', 'Buy & Sell', 'Acheter Vendre');
INSERT INTO `language` VALUES (897, 'deposit,_withdraw,_transfer', 'Deposit, Withdraw, Transfer', 'Dépôt, Retrait, Transfert');
INSERT INTO `language` VALUES (898, 'see_all_pending_withdraw', 'See All Pending Withdraw', 'Voir Tous Les Retraits En Attente');
INSERT INTO `language` VALUES (899, 'see_all_trade_history', 'See All Trade History', 'Voir Toute L\'histoire Du Commerce');
INSERT INTO `language` VALUES (900, 'user_growth_rate', 'USER GROWTH RATE', 'TAUX DE CROISSANCE DES UTILISATEURS');
INSERT INTO `language` VALUES (901, 'email_sms_settings', 'Email Sms Settings', 'Paramètres De Messagerie électronique');
INSERT INTO `language` VALUES (902, 'email-sms-settings', 'Email-sms-settings', 'Email-sms-settings');
INSERT INTO `language` VALUES (903, 'fees_collection', 'Fees Collection', 'Perception Des Frais');
INSERT INTO `language` VALUES (904, 'create_user', 'Create User', 'Créer Un Utilisateur');
INSERT INTO `language` VALUES (905, 'create_admin', 'Create Admin', 'Créer Un Administrateur');
INSERT INTO `language` VALUES (906, 'add-ons', 'Add-ons', 'Add-ons');
INSERT INTO `language` VALUES (907, 'max_sell_currency_amount', 'Max Sell Currency Amount', 'Montant Maximal De La Devise De Vente');
INSERT INTO `language` VALUES (908, 'max_buy_currency_amount', 'Max Buy Currency Amount', 'Montant Maximal De La Devise D\'achat');
INSERT INTO `language` VALUES (909, 'account', 'Account', 'Compte');
INSERT INTO `language` VALUES (910, 'google_captcha', 'Google Captcha', 'Google Capture');
INSERT INTO `language` VALUES (911, 'add_captcha_at_your_domain', 'Add captcha at your domain', 'Domaine De Configuration');
INSERT INTO `language` VALUES (912, 'pages', 'Pages', 'Pages');
INSERT INTO `language` VALUES (913, 'useful_links', 'Useful Links', 'Liens Utiles');
INSERT INTO `language` VALUES (914, 'check_your_email_server', 'Check Your Email Server', 'Vérifiez Votre Serveur De Messagerie');
INSERT INTO `language` VALUES (915, 'check_your_sms_gateway_', 'Check Your Sms Gateway ', 'Vérifiez Votre Passerelle SMS');
INSERT INTO `language` VALUES (916, 'mobile_no', 'Mobile No', 'Mobile Non');
INSERT INTO `language` VALUES (917, 'email_gateway_setup', 'Email Gateway Setup', 'Configuration De La Passerelle De Messagerie');
INSERT INTO `language` VALUES (918, 'sms_gateway_setup', 'SMS Gateway Setup', 'Configuration De La Passerelle SMS');
INSERT INTO `language` VALUES (919, 'check_your_sms_gateway', 'Check Your Sms Gateway', 'Vérifiez Votre Passerelle SMS');
INSERT INTO `language` VALUES (920, 'logo_type', 'Logo Type', 'Type De Logo');
INSERT INTO `language` VALUES (921, 'log_type', 'Log Type', 'Type De Journal');
INSERT INTO `language` VALUES (922, 'body_background_color', 'Body Background Color', 'Couleur D\'arrière-plan Du Corps');
INSERT INTO `language` VALUES (923, 'body_font_color', 'Body Font Color', 'Couleur De La Police Du Corps');
INSERT INTO `language` VALUES (924, 'top_footer_horizontal_border_color', 'Top Footer Horizontal Border Color', 'Couleur De La Bordure Horizontale Du Pied De Page Supérieur');
INSERT INTO `language` VALUES (925, 'footer__menu_border_color', 'Footer  Menu Border Color', 'Couleur De La Bordure Du Menu Du Pied De Page');
INSERT INTO `language` VALUES (926, 'footer_menu_border_color', 'Footer Menu Border Color', 'Couleur De La Bordure Du Menu Du Pied De Page');
INSERT INTO `language` VALUES (927, 'bottom_footer_background_color', 'Bottom Footer Background Color', 'Couleur D\'arrière-plan Du Pied De Page Inférieur');
INSERT INTO `language` VALUES (928, 'bottom_footer_font_color', 'Bottom Footer Font Color', 'Couleur De Police Du Pied De Page Inférieur');
INSERT INTO `language` VALUES (929, 'form_background_color', 'Form Background Color', 'Couleur D\'arrière-plan Du Formulaire');
INSERT INTO `language` VALUES (930, 'form_border_color', 'Form Border Color', 'Couleur De La Bordure Du Formulaire');
INSERT INTO `language` VALUES (931, 'form_label_color', 'Form Label Color', 'Couleur De L\'étiquette Du Formulaire');
INSERT INTO `language` VALUES (932, 'form_input_field_background_color', 'Form Input Field Background Color', '');
INSERT INTO `language` VALUES (933, 'input_field_border_color', 'Input Field Border Color', 'Couleur De La Bordure Du Champ De Saisie');
INSERT INTO `language` VALUES (934, 'input_field_color', 'Input Field Color', 'Couleur Du Champ De Saisie');
INSERT INTO `language` VALUES (935, 'verify_profile', 'Verify Profile', 'Vérifier Le Profil');
INSERT INTO `language` VALUES (936, 'contact_with_us', 'Contact With Us', 'En Contact Avec Nous');
INSERT INTO `language` VALUES (937, 'working_hours', 'Working Hours', 'Heures D\'ouverture');
INSERT INTO `language` VALUES (938, 'phone_number', 'Phone Number', 'Numéro De Téléphone');
INSERT INTO `language` VALUES (939, 'bank_payment', 'Bank Payment', 'Paiement Bancaire');
INSERT INTO `language` VALUES (940, 'themes_setting', 'Themes Setting', 'Réglage Des Thèmes');
INSERT INTO `language` VALUES (941, 'page_content_list', 'Page Content List', 'Liste Du Contenu De La Page');
INSERT INTO `language` VALUES (942, 'notice_list', 'Notice List', 'Liste Des Avis');
INSERT INTO `language` VALUES (943, 'category_list', 'Category List', 'Liste Des Catégories');
INSERT INTO `language` VALUES (944, 'social_link_list', 'Social Link List', 'Liste De Liens Sociaux');
INSERT INTO `language` VALUES (945, 'advertisement_list', 'Advertisement List', 'Liste Des Publicités');
INSERT INTO `language` VALUES (946, 'web_language_list', 'Web Language List', 'Liste Des Langues Web');
INSERT INTO `language` VALUES (947, 'coinpayment', 'Coinpayment', 'Paiement Par Pièces');
INSERT INTO `language` VALUES (948, 'gourl', 'Gourl', 'Gourle');
INSERT INTO `language` VALUES (949, 'paypal', 'Paypal', 'Pay Pal');
INSERT INTO `language` VALUES (950, 'paystack', 'Paystack', 'Paie');
INSERT INTO `language` VALUES (951, 'transaction_setup', 'Transaction Setup', 'Configuration Des Transactions');
INSERT INTO `language` VALUES (952, 'external_api_list', 'External Api List', 'Liste D\'API Externes');
INSERT INTO `language` VALUES (953, 'bank_payment', 'Bank', 'Bank');
INSERT INTO `language` VALUES (954, 'coinpayment', 'Coinpayment', 'Coinpayment');
INSERT INTO `language` VALUES (955, 'gourl', 'Gourl', 'Gourl');
INSERT INTO `language` VALUES (956, 'paypal', 'Paypal', 'Paypal');
INSERT INTO `language` VALUES (957, 'paystack', 'Paystack', 'Paystack');
INSERT INTO `language` VALUES (958, 'stripe', 'Stripe', 'Stripe');
INSERT INTO `language` VALUES (959, 'token_payment', 'Token', 'Token');
INSERT INTO `language` VALUES (960, 'page_content_list', 'Page Content List', 'Page Content List');
INSERT INTO `language` VALUES (961, 'themes_setting', 'Themes Setting', 'Themes Setting');
INSERT INTO `language` VALUES (962, 'notice_list', 'Notice List', 'Notice List');
INSERT INTO `language` VALUES (963, 'category_list', 'Category List', 'Category List');
INSERT INTO `language` VALUES (964, 'social_link_list', 'Social Link', 'Social Link');
INSERT INTO `language` VALUES (965, 'advertisement_list', 'Advertisement List', 'Advertisement List');
INSERT INTO `language` VALUES (966, 'web_language_list', 'Web Language List', 'Web Language List');
INSERT INTO `language` VALUES (967, 'transaction_setup', 'Transaction Setup', 'Transaction Setup');
INSERT INTO `language` VALUES (968, 'external_api_list', 'External Api List', 'External Api List');
INSERT INTO `language` VALUES (969, 'verify_users', 'Verify Users', 'Verify Users');
INSERT INTO `language` VALUES (970, 'subscriber_list', 'Subscriber List', 'Subscriber List');
INSERT INTO `language` VALUES (971, 'order_book', 'Order Book', 'Order Book');
INSERT INTO `language` VALUES (972, 'trades', 'trades', 'trades');
INSERT INTO `language` VALUES (973, 'order_placement', 'Order Placement', 'Order Placement');
INSERT INTO `language` VALUES (974, 'search_pair', 'Search Pair', 'Search Pair');
INSERT INTO `language` VALUES (975, 'more', 'More', 'More');
INSERT INTO `language` VALUES (976, 'from_date', 'From Date', 'Partir De La Date');
INSERT INTO `language` VALUES (977, 'to_date', 'To Date', 'À Ce Jour');
INSERT INTO `language` VALUES (978, 'coins', 'Coins', 'Pièces De Monnaie');
INSERT INTO `language` VALUES (979, 'select_coin', 'Select Coin', 'Sélectionnez La Pièce');
INSERT INTO `language` VALUES (980, 'select_status', 'Select Status', 'Sélectionnez Le Statut');
INSERT INTO `language` VALUES (981, 'trade_type', 'Trade Type', 'Type De Commerce');
INSERT INTO `language` VALUES (982, 'select_trade_type', 'Select Trade Type', 'Sélectionnez Le Type De Commerce');
INSERT INTO `language` VALUES (983, 'open_trade', 'Open Trade', 'Commerce Ouvert');
INSERT INTO `language` VALUES (984, 'complete_trade', 'Complete Trade', 'Commerce Complet');
INSERT INTO `language` VALUES (985, 'canceled_trade', 'Canceled Trade', 'Commerce Annulé');
INSERT INTO `language` VALUES (986, 'bid_type', 'Bid Type', 'Type D\'enchère');
INSERT INTO `language` VALUES (987, 'select_bid_type', 'Select Bid Type', 'Sélectionnez Le Type D\'enchère');
INSERT INTO `language` VALUES (988, 'receiver', 'Receiver', 'Receveur');
INSERT INTO `language` VALUES (989, 'your_xx_messenger_address_recommended_for_max_security', 'Your XX Messenger Address - Recommended for Max Security', 'Votre adresse XX Messenger - Recommandée pour Max Security');
INSERT INTO `language` VALUES (990, 'the_filled_data_is_correct', 'The filled data is correct', 'Les données remplies sont correctes');
INSERT INTO `language` VALUES (991, 'xx_messenger', 'XX Messenger', 'XX Messager');
INSERT INTO `language` VALUES (992, 'select_type', 'Select Type', 'Sélectionner le genre');
INSERT INTO `language` VALUES (993, 'by_usdc', 'by USDC', 'par l\'USDC');
INSERT INTO `language` VALUES (994, 'by_usde', 'by USDE', 'par l\'USDE');
INSERT INTO `language` VALUES (995, 'by_usdt', 'by USDT', 'par l\'USDT');
INSERT INTO `language` VALUES (996, 'blockchain_address_where_you_want_to_receive_your_tokens', 'Blockchain address where you want to receive your tokens', 'Adresse Blockchain où vous souhaitez recevoir vos jetons');
INSERT INTO `language` VALUES (997, 'network', 'Network', 'Réseau');
INSERT INTO `language` VALUES (998, 'your_xx_messenger_address', 'Your XX Messenger Address (for extra layer of security - we will send you a question)', 'Votre adresse XX Messenger (pour une couche de sécurité supplémentaire - nous vous enverrons une question)');
INSERT INTO `language` VALUES (999, 'unable_to_use_this_token', 'Unable to use this token.', 'Impossible d\'utiliser ce jeton.');
INSERT INTO `language` VALUES (1000, 'blockchain_address', 'Blockchain Address', 'Adresse de la chaîne de blocs');

SET FOREIGN_KEY_CHECKS = 1;
